// Fifteen distinct admin perspectives with round-dependent payloads/order/viewports.
// Real browser and application assets; synthetic API state, no host configuration writes.
const {chromium}=require(process.env.PLAYWRIGHT_MODULE||'playwright');
const assert=require('node:assert/strict'),fs=require('node:fs/promises'),path=require('node:path');
(async()=>{
 const browser=await chromium.launch(),round=Number(process.env.GAUNTLET_ROUND||1),results=[];
 try{for(let slot=0;slot<15;slot++){
  const profile=(slot+round-1)%15+1,page=await browser.newPage({viewport:{width:round%2?1280:390,height:900}});page.setDefaultTimeout(5000);
  const calls=[],errors=[],suffix=' '+round,permissions={read:true,write:false,upload:true,shell:false,internet:false,hooks:false};
  const service=(models=[])=>({added:true,enabled:!!models.length,models,projects:['sem-projeto'],permissions:{...permissions},mode:'native',integrations:['mcp:drive','plugin:example@fixture']});
  const state={settings:{services:{codex:service(['fixture']),claude:service(['sonnet']),local:service(['qwen']),deepseek:service(['deepseek-flash'])},projects:[],logins:[],port:8095,tailnet_port:8095,uploads_enabled:true},inventory:{platform:'Linux',services:[{id:'codex',name:'Codex CLI',found:true},{id:'claude',name:'Claude Code',found:true},{id:'local',name:'Local model',found:true,models:['qwen'],runtimes:[]},{id:'deepseek',name:'DeepSeek',found:true,api:true}],projects:[],network:{online:true}},authentication:{codex:true,claude:true,local:true,deepseek:true},models:{codex:{fixture:['low'],'other-model':['low']},claude:{sonnet:['configured']},local:{qwen:['low']},deepseek:{'deepseek-flash':['configured']}},integrations:{codex:[{id:'mcp:drive',name:'Drive',kind:'mcp'},{id:'plugin:example@fixture',name:'Example',kind:'plugin'}],claude:[],local:[],deepseek:[]},local_profiles:{'/fixture/model.gguf':{model_file:'/fixture/model.gguf',binary:'/fixture/llama-server',description:'Initial profile',performance:{threads:'4','n-gpu-layers':'0'},permissions,capabilities:{tools:true},allowed_roots:[]}},operations:[],credentials:{deepseek:true},status:{running:false,local_url:'http://127.0.0.1:8095/'}};
  const alternative='other-model-'+round;state.models.codex[alternative]=state.models.codex['other-model'];delete state.models.codex['other-model'];
  let failSave=false,holdSave=false,releaseSave,failCatalog=false,failState=false;
  page.on('pageerror',e=>errors.push(e.message));
  await page.route('http://admin.test/**',async route=>{
   const u=new URL(route.request().url()),p=u.pathname.slice(5);
   if(u.pathname.startsWith('/api/')){
    const data=route.request().method()==='POST'?route.request().postDataJSON():null;calls.push({path:p,data});let response={};
    if(p==='state'){if(failState)return route.fulfill({status:503,json:{error:'State unavailable'}});response=state;}
    if(p==='dashboard')response={available:true,checked_at:Date.now()/1000,requests_per_second:0,active:0,queued:0,input_tokens:null,output_tokens:null,measured_jobs:0,latest_output_tokens_per_second:null,hardware:{cpu_percent:0,memory_used:100,memory_total:1000,gpus:[]},recent:[]};
    if(p==='scan')response=state.inventory;
    if(p==='settings'||p==='local-profile'){
     if(holdSave)await new Promise(resolve=>releaseSave=resolve);
     if(failSave)return route.fulfill({status:400,json:{error:'Controlled failure '+round}});
     if(p==='settings')state.settings=data;else{state.local_profiles[data.model_file]=data;response=data;}
    }
    if(p==='check')response={authenticated:true,models:state.models[data.provider]};
    if(p==='integration-catalog'){if(failCatalog)return route.fulfill({status:503,json:{error:'Catalog unavailable '+round}});response={items:[{id:'plugin:example@fixture',name:'Example',kind:'plugin',status:'installed'},{id:'plugin:new@fixture',name:'New '+round,kind:'plugin',status:'available'}],warnings:[]};}
    if(p==='integration'){state.operations=[{id:'operation-1',state:'failed',output:'Controlled failure'}];response={id:'operation-1'};}
    if(p==='settings-import')response={services:['codex'],projects:0,local_profile:false};
    if(p.startsWith('folders'))response={path:'/fixture',parent:'/',directories:[{name:'project'+suffix,path:'/fixture/project'+suffix}],truncated:false};
    return route.fulfill({json:response});
   }
   const file=u.pathname==='/'?'index.html':u.pathname.slice(1);
   return route.fulfill({body:await fs.readFile(path.join(__dirname,file.startsWith('assets/')?'../tail_ui':'../control',file)),contentType:file.endsWith('.js')?'text/javascript':file.endsWith('.css')?'text/css':file.endsWith('.svg')?'image/svg+xml':'text/html'});
  });
  const edit=async(name='Codex CLI')=>{await page.locator('[data-panel=provedores]').click();await page.getByRole('button',{name:'Edit '+name,exact:true}).click();await page.locator('#provider-dialog').waitFor();};
  const models=()=>page.locator('#provider-cards .model-list input');
  const finish=()=>page.waitForFunction(()=>!working);
  try{
   await page.goto('http://admin.test/');await page.locator('[data-configured-provider=codex]').waitFor({state:'attached'});await finish();
   if(profile===1){for(const panel of ['provedores','execucoes','home']){await page.locator('[data-panel='+panel+']').click();await page.waitForFunction(panel=>document.querySelector('[aria-current=page]')?.dataset.panel===panel,panel);}await page.reload();await finish();assert.equal(await page.locator('[aria-current=page]').getAttribute('data-panel'),'home');}
   if(profile===2){await edit();await models().nth(1).check();holdSave=true;await page.click('#save');await page.waitForFunction(()=>working);assert(await models().nth(0).isDisabled(),'Provider inputs must be locked while saving to avoid losing newer edits');releaseSave();await finish();assert.equal(calls.filter(x=>x.path==='settings').length,1);}
   if(profile===3){await edit();await models().nth(1).check();failSave=true;await page.click('#save');await finish();assert(await models().nth(1).isChecked());assert(await page.locator('#provider-dialog').isVisible());assert.match(await page.locator('#feedback').innerText(),/Controlled failure/);failSave=false;await page.click('#save');await finish();assert(state.settings.services.codex.models.includes(alternative));}
   if(profile===4){await edit();await page.getByRole('button',{name:'Connectors',exact:true}).focus();await page.keyboard.press('Enter');await page.getByRole('checkbox',{name:/Drive/}).uncheck();page.once('dialog',d=>d.dismiss());await page.keyboard.press('Escape');assert(await page.locator('#provider-dialog').evaluate(e=>e.open));page.once('dialog',d=>d.accept());await page.keyboard.press('Escape');await finish();await page.waitForFunction(()=>!document.querySelector('#provider-dialog').open);assert.equal(await page.evaluate(()=>document.activeElement.getAttribute('aria-label')),'Edit Codex CLI');}
   if(profile===5){await page.setViewportSize({width:[320,390,768,1024][round%4],height:844});await edit();for(const tab of ['Model and hardware','Plugins','Connectors']){await page.getByRole('button',{name:tab,exact:true}).click();assert(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),'No horizontal page overflow');}await page.screenshot({path:'/tmp/tail-admin-gauntlet/mobile-round'+round+'.png'});}
   if(profile===6){await page.click('#theme');await page.locator('[data-config-tab=mcp]').click();await page.selectOption('#mcp-default-model',JSON.stringify(['codex','fixture']));await page.selectOption('#mcp-default-effort','low');await page.click('#save-mcp');await finish();assert.deepEqual(state.settings.mcp_defaults,{backend:'codex',model:'fixture',effort:'low'});assert(!/Start the harness to apply/.test(await page.locator('#mcp-feedback').innerText()),'MCP save must not claim manual restart when automatic application is implemented');}
   if(profile===7){await page.locator('[data-panel=provedores]').click();assert.equal(await page.locator('[data-configured-provider=codex] .configured-models svg').count(),1,'Configured model name needs its provider icon beside it');await edit();await page.getByRole('button',{name:'Plugins',exact:true}).click();await page.waitForTimeout(100);const missing=await page.locator('button').evaluateAll(es=>es.filter(e=>e.getClientRects().length&&(!e.title||!e.querySelector('svg,.provider-mark'))).map(e=>e.id||e.textContent));assert.deepEqual(missing,[]);}
   if(profile===8){state.integrations.codex.push({id:'mcp:hostile',name:'<img src=x onerror="window.pwned=1">'+suffix,kind:'mcp'});await page.reload();await finish();await edit();await page.getByRole('button',{name:'Connectors',exact:true}).click();assert.equal(await page.locator('#integration-selection img').count(),0);assert.equal(await page.evaluate(()=>window.pwned),undefined);assert.match(await page.locator('#integration-selection').innerText(),/<img/i);}
   if(profile===9){await edit();await page.getByRole('button',{name:'Connectors',exact:true}).click();await page.selectOption('#integration-transport','stdio');await page.fill('#integration-name','test'+round);await page.fill('#integration-source',['[','{}','[]','[1]','[""]','null','"command"','[true]','[["nested"]]','["p",null]'][round-1]);await page.click('#integration-run');await finish();assert.equal(calls.filter(x=>x.path==='integration').length,0);assert.match(await page.locator('#feedback').innerText(),/JSON list.*command|command.*JSON list/i,'Malformed local connector command needs an actionable error');}
   if(profile===10){await edit();await models().nth(1).check();await page.click('#save');await finish();assert(!await page.locator('#provider-dialog').evaluate(e=>e.open));await edit();assert(await models().nth(1).isChecked());assert.equal(calls.filter(x=>x.path==='settings').length,1);}
   if(profile===11){await page.locator('[data-panel=provedores]').click();await page.click('#manage-network');await page.locator('#import-settings').setInputFiles({name:'config.json',mimeType:'application/json',buffer:Buffer.from(round%2?'{':' '.repeat(60001))});await finish();assert.equal(calls.filter(x=>x.path==='settings-import').length,0);assert.match(await page.locator('#network-feedback').innerText(),round%2?/JSON/i:/too large/i,'Invalid import must explain file format');assert(!await page.locator('#import-preview').isVisible());}
   if(profile===12){await edit();await models().nth(1).check();const prevented=await page.evaluate(()=>{const e=new Event('beforeunload',{cancelable:true});window.dispatchEvent(e);return e.defaultPrevented;});assert(prevented,'Unsaved provider changes must warn before reload/close');}
   if(profile===13){await edit('Local Model via Codex');await page.locator('#hardware-editor-details summary').click();await page.fill('#profile-description','Draft '+round);holdSave=true;await page.click('#profile-save');await page.waitForFunction(()=>working);assert(await page.locator('#profile-description').isDisabled(),'Hardware inputs must be locked during profile save');releaseSave();await finish();assert.equal(state.local_profiles['/fixture/model.gguf'].description,'Draft '+round);}
   if(profile===14){await edit();failCatalog=true;await page.getByRole('button',{name:'Plugins',exact:true}).click();await page.locator('#catalog-status').filter({hasText:'Catalog unavailable'}).waitFor();assert(await page.getByRole('checkbox',{name:/Example/}).isChecked());failCatalog=false;await page.click('#catalog-refresh');await page.getByRole('button',{name:'Install New '+round,exact:true}).waitFor();assert(await page.getByRole('checkbox',{name:/Example/}).isChecked());}
   if(profile===15){await edit();await page.getByRole('button',{name:'Plugins',exact:true}).click();await page.getByRole('button',{name:'Install New '+round,exact:true}).click();await finish();await page.locator('#operation-retry').waitFor();assert.match(await page.locator('#operation-message').innerText(),/failed/i);await page.click('#operation-retry');await finish();assert.equal(calls.filter(x=>x.path==='integration').length,2);}
   assert.deepEqual(errors,[]);results.push({profile,round,status:'pass'});console.log('P'+profile+' R'+round+' pass');
  }catch(e){results.push({profile,round,status:'fail',error:e.message});console.log('P'+profile+' R'+round+' fail '+e.message);}finally{releaseSave?.();await page.close();}
 }}finally{await browser.close();if(process.env.GAUNTLET_OUTPUT)await fs.writeFile(process.env.GAUNTLET_OUTPUT,JSON.stringify(results,null,2)+'\n');}
 if(results.some(r=>r.status!=='pass'))process.exitCode=1;
})().catch(e=>{console.error(e);process.exitCode=1;});
