const {chromium}=require(process.env.PLAYWRIGHT_MODULE||'playwright');
const assert=require('node:assert/strict');
(async()=>{const b=await chromium.launch();const p=await b.newPage({viewport:{width:1440,height:1000}});const errors=[],saved=[];p.on('pageerror',e=>errors.push(e.message));p.on('dialog',d=>d.accept());
 const empty=id=>({added:false,enabled:false,models:[],projects:['sem-projeto'],permissions:{read:false,write:false,upload:false,shell:false,internet:false,hooks:false},mode:['local','deepseek'].includes(id)?'native':'scoped',integrations:[]});
 const state={settings:{services:Object.fromEntries(['codex','claude','local','deepseek'].map(id=>[id,empty(id)])),projects:[],logins:[],port:8095,tailnet_port:8095,uploads_enabled:false},inventory:{platform:'Linux',services:[{id:'codex',name:'Codex CLI',found:true},{id:'claude',name:'Claude Code',found:true},{id:'local',name:'Modelo local',found:false},{id:'deepseek',name:'DeepSeek',api:true,found:true}],projects:[{name:'Demo',path:'/workspace/demo'}],network:{online:true}},authentication:{},models:{},integrations:{codex:[{id:'mcp:drive',name:'Drive',kind:'mcp'}],claude:[],local:[],deepseek:[]},operations:[],credentials:{},status:{running:false,local_url:'http://127.0.0.1:8095/',remote_url:'http://demo.tailnet:8095/',shared:false}};

const idle=()=>p.waitForFunction(()=>!document.body.hasAttribute('aria-busy'));
let authenticated=true,catalog='alpha';
await p.route('**/api/**',async route=>{const req=route.request(),name=new URL(req.url()).pathname.slice(5),data=req.method()==='POST'?req.postDataJSON():null;let result={};
if(name==='state')result=state;
else if(name==='scan')result=state.inventory;
else if(name==='check'){result={authenticated,models:data.provider==='claude'?{sonnet:['configured']}:{[catalog]:['low','high']}};state.authentication[data.provider]=authenticated;state.models[data.provider]=result.models;}
else if(name==='settings'){state.settings=structuredClone(data);saved.push(structuredClone(data));result={saved:true};}
return route.fulfill({json:result});});
await p.goto(process.env.ADMIN_URL||'http://127.0.0.1:18267/');await p.waitForFunction(()=>document.querySelector('#configured-providers')&&!document.body.hasAttribute('aria-busy'));await p.click('#add-provider');await p.locator('#provider-options').getByText('Codex CLI',{exact:false}).click();await p.waitForFunction(()=>!document.body.hasAttribute('aria-busy'));
await p.locator('[data-provider=codex]').getByRole('button',{name:'Verificar conta',exact:true}).click();await p.waitForFunction(()=>!document.body.hasAttribute('aria-busy'));await p.locator('[data-provider=codex]').getByLabel('alpha',{exact:true}).check();await p.locator('[data-provider=codex]').getByLabel('Disponibilizar este serviço',{exact:true}).check();await p.click('#wizard-next');await p.click('#wizard-next');await p.click('#save');await p.waitForFunction(()=>document.querySelector('#dirty').textContent==='Configurações salvas');assert.deepEqual(saved.at(-1).services.codex.models,['alpha']);await p.reload();await p.locator('[data-configured-provider=codex]').getByRole('button',{name:'Editar Codex CLI',exact:true}).click();await p.waitForFunction(()=>!document.body.hasAttribute('aria-busy'));assert(await p.locator('[data-provider=codex]').getByLabel('alpha',{exact:true}).isChecked());

catalog='beta';await p.locator('[data-provider=codex]').getByRole('button',{name:'Verificar conta',exact:true}).click();await idle();assert.match(await p.locator('[data-provider=codex]').innerText(),/Indisponível/);const before=saved.length;await p.click('#save');await idle();assert.equal(saved.length,before);assert.match(await p.locator('#feedback').innerText(),/modelo/i);
await p.locator('[data-provider=codex]').getByLabel('alpha',{exact:false}).uncheck();await p.locator('[data-provider=codex]').getByLabel('beta',{exact:true}).check();await p.click('#save');await idle();assert.deepEqual(saved.at(-1).services.codex.models,['beta']);
await p.click('#wizard-cancel');await idle();await p.click('#add-provider');await idle();await p.locator('#provider-options').getByText('Claude Code',{exact:false}).click();authenticated=false;await p.locator('[data-provider=claude]').getByRole('button',{name:'Verificar conta',exact:true}).click();await idle();assert.match(await p.locator('#feedback').innerText(),/Use Entrar/);await p.locator('[data-provider=claude]').getByLabel('sonnet',{exact:true}).check();await p.locator('[data-provider=claude]').getByLabel('Disponibilizar este serviço',{exact:true}).check();await p.click('#wizard-next');await p.click('#wizard-next');assert.match(await p.locator('#provider-review').innerText(),/autori|autent|login/i);const count=saved.length;await p.click('#save');await idle();assert.equal(saved.length,count);assert.match(await p.locator('#feedback').innerText(),/Entrar|autori|autent/i);
await p.click('#wizard-back');await p.click('#wizard-back');await p.locator('[data-provider=claude]').getByLabel('Disponibilizar este serviço',{exact:true}).uncheck();await p.click('#wizard-next');await p.click('#wizard-next');await p.click('#save');await idle();assert.equal(state.settings.services.claude.enabled,false);
authenticated=true;await p.locator('#inspector-tabs').getByText('Modelo e hardware').click();await p.locator('[data-provider=claude]').getByRole('button',{name:'Verificar conta',exact:true}).click();await idle();await p.locator('[data-provider=claude]').getByLabel('Disponibilizar este serviço',{exact:true}).check();await p.click('#save');await idle();assert.equal(state.settings.services.claude.enabled,true);await p.reload();await p.waitForFunction(()=>document.querySelectorAll('#configured-providers article').length===2&&!document.body.hasAttribute('aria-busy'));assert.deepEqual(state.settings.services.codex.models,['beta']);assert.deepEqual(state.settings.services.claude.models,['sonnet']);
for(const theme of ['violet-bordeaux','porcelain','mineral-rose','amethyst','petroleum','arizona']){await p.click('#theme');await p.locator('[data-theme-choice='+theme+']').click();assert.equal(await p.locator('html').getAttribute('data-palette'),theme);await p.click('#appearance-close');}
assert.deepEqual(errors,[]);console.log('PASS gauntlet: Codex/Claude cadastro, catálogo obsoleto, autenticação recusada, salvar desativado, reautorizar, persistência e seis temas');await b.close();})().catch(e=>{console.error(e);process.exit(1)});
