const {chromium}=require(process.env.PLAYWRIGHT_MODULE||'playwright');
const assert=require('node:assert/strict');
(async()=>{const browser=await chromium.launch();try{
 const page=await browser.newPage();let discard=false,confirmed=0,quotaDelay=0;
 page.on('dialog',async d=>{confirmed++;await(discard?d.accept():d.dismiss());});
 await page.route('**/v1/**',async r=>{
  const path=new URL(r.request().url()).pathname;let data={};
  if(path==='/v1/projects')data={projects:['sem-projeto','demo'],details:{demo:{label:'Projeto de trabalho'}}};
  if(path==='/v1/models')data={models:[{id:'gpt-5.6-sol',backend:'codex',name:'Sol',efforts:['low','high']},{id:'sonnet',backend:'claude',name:'Sonnet',efforts:['low','high']}],providers:{codex:true,claude:true},uploads_enabled:false};
  if(path==='/v1/usage'&&quotaDelay)await new Promise(resolve=>setTimeout(resolve,quotaDelay));
  if(path==='/v1/usage')data=new URL(r.request().url()).searchParams.get('backend')==='claude'?{available:false,backend:'claude'}:{available:true,backend:'codex',rateLimits:{primary:{usedPercent:25,windowDurationMins:300,resetsAt:1999999999}}};
  if(path==='/v1/conversations')data={conversations:[]};
  return r.fulfill({json:data});
 });
 await page.goto(process.env.HARNESS_URL||'http://127.0.0.1:8095/');
 await page.selectOption('#model','gpt-5.6-sol');await page.waitForFunction(()=>document.querySelector('#quota-short').textContent.includes('75%'));
 await page.selectOption('#model','sonnet');
 await page.waitForFunction(()=>!document.querySelector('#quota-short').textContent.includes('75%'),null,{timeout:3000});
 assert.match(await page.locator('#quota-short').innerText(),/Claude|indisponível|não disponível/);
 quotaDelay=250;await page.selectOption('#model','gpt-5.6-sol');await page.selectOption('#model','sonnet');await page.waitForTimeout(350);
 assert.match(await page.locator('#quota-short').innerText(),/Claude|indisponível|não disponível/,'Late OpenAI quota must not overwrite Claude status');
 await page.fill('#prompt','Rascunho importante da auditoria');
 await page.getByRole('button',{name:'Projeto de trabalho',exact:true}).click();
 assert.equal(await page.locator('#prompt').inputValue(),'Rascunho importante da auditoria');
 await page.locator('.project-new').click();
 assert.equal(await page.locator('#prompt').inputValue(),'Rascunho importante da auditoria');
 assert(confirmed>0,'Starting a new chat should confirm discarding a nonempty draft');
 discard=true;await page.locator('.project-new').click();assert.equal(await page.locator('#prompt').inputValue(),'');
 console.log('PASS: Codex to Claude truthful quota, project selection preserves draft, new chat confirms discard');
}finally{await browser.close();}})().catch(e=>{console.error(e);process.exitCode=1;});
