const {chromium}=require(process.env.PLAYWRIGHT_MODULE||'playwright');
const assert=require('node:assert/strict');
(async()=>{const b=await chromium.launch();try{
 const p=await b.newPage({viewport:{width:1440,height:1000}}),errors=[];p.on('pageerror',e=>errors.push(e.message));
 const turn=id=>({id,project:'sem-projeto',state:'completed',request:{prompt:'Pergunta '+id,model:'fixture',backend:'local',effort:'low'},result:{answer:'Resposta '+id,model:'fixture',metrics:{output_tokens:id==='one'?11:22},references:['referência '+id]}});
 await p.route('**/v1/**',async r=>{const path=new URL(r.request().url()).pathname;let data={};
  if(path==='/v1/projects')data={projects:['sem-projeto'],details:{}};
  if(path==='/v1/models')data={models:[{id:'fixture',name:'Modelo de teste',backend:'local',efforts:['low']}],providers:{local:true},uploads_enabled:false};
  if(path==='/v1/conversations')data={conversations:[{id:'conversation',title:'Conversa com duas respostas',project:'sem-projeto',state:'completed'}]};
  if(path==='/v1/conversations/conversation')data={turns:[turn('one'),turn('two')]};
  if(path==='/v1/jobs'&&r.request().method()==='POST')data={job_id:'three'};
  if(path.startsWith('/v1/jobs/')){const id=path.split('/')[3];data=turn(id);
   if(path.endsWith('/events'))return r.fulfill({contentType:'text/event-stream',body:[{id:1,type:'tool_start',data:{tool:'ferramenta-'+id}},{id:2,type:'answer_delta',data:{text:'Resposta '+id}},{id:3,type:'completed',data:{}}].map(e=>'data: '+JSON.stringify(e)+'\n\n').join('')});
  }
  return r.fulfill({json:data});
 });
 await p.goto(process.env.HARNESS_URL||'http://127.0.0.1:8095/');
 await p.locator('.conversation-row>button').first().click();
 await p.waitForFunction(()=>document.querySelectorAll('.response-detail-card').length===2&&!document.querySelector('#send').hidden);
 assert.equal(await p.locator('#messages summary').filter({hasText:'Etapas e ferramentas'}).count(),0);
 assert.equal(await p.locator('#messages summary').filter({hasText:'Métricas, referências e alterações'}).count(),0);
 const old=p.locator('.response-detail-card[data-job=one]');
 await old.locator('summary').filter({hasText:'Etapas e ferramentas'}).click();
 await old.getByText('Usando ferramenta · ferramenta-one',{exact:false}).waitFor();
 await old.locator('summary').filter({hasText:'Métricas, referências e alterações'}).click();
 assert.match(await old.innerText(),/referência one/);assert.doesNotMatch(await old.innerText(),/referência two/);
 await p.fill('#prompt','Terceira pergunta');await p.click('#send');
 await p.waitForFunction(()=>document.querySelectorAll('.response-detail-card').length===3&&!document.querySelector('#send').hidden);
 const newest=p.locator('.response-detail-card[data-job=three]');
 await newest.locator('summary').filter({hasText:'Etapas e ferramentas'}).click();
 assert.match(await newest.innerText(),/ferramenta-three/);
 await newest.locator('summary').filter({hasText:'Métricas, referências e alterações'}).click();assert.match(await newest.innerText(),/referência three/);
 await p.fill('#prompt','Rascunho preservado');await p.click('#settings');await p.locator('[data-theme-choice=arizona]').click();await p.click('#settings-close');
 assert.equal(await p.locator('#prompt').inputValue(),'Rascunho preservado');assert.equal(await p.locator('.response-detail-card').count(),3);
 await p.setViewportSize({width:390,height:844});await p.click('#activity-close');
 await p.locator('.inspect-execution').first().click();
 assert(await p.locator('#activity-panel').isVisible());assert.equal(await p.evaluate(()=>document.activeElement.dataset.job),'one');
 assert(await p.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));
 await p.screenshot({path:'/tmp/harness-side-details-mobile.png'});
 await p.keyboard.press('Escape');assert(!await p.locator('#activity-panel').isVisible());
 assert.deepEqual(errors,[]);console.log('PASS: per-response sidebar tools/metrics, history replay, new streamed response, theme, mobile inspection and keyboard');
}finally{await b.close();}})().catch(e=>{console.error(e);process.exitCode=1;});
