// Real HTTP persistence/gates and real browser controls; inference alone is synthetic.
const {chromium}=require(process.env.PLAYWRIGHT_MODULE||'playwright');
const assert=require('node:assert/strict'),fs=require('node:fs/promises'),os=require('node:os'),path=require('node:path'),{spawn}=require('node:child_process');
(async()=>{const folder=await fs.mkdtemp(path.join(os.tmpdir(),'maestro-entry-'));const proc=spawn(process.env.PYTHON||path.join(__dirname,'../.venv/bin/python'),['-m','tests.maestro_browser_fixture',folder],{cwd:path.join(__dirname,'..'),env:{...process.env,HOME:folder},stdio:['ignore','pipe','pipe']});let log='';proc.stderr.on('data',s=>log+=s);let browser;
try{let ready;for(let i=0;i<100;i++){try{ready=JSON.parse(await fs.readFile(path.join(folder,'ready.json')));const r=await fetch('http://127.0.0.1:'+ready.port+'/v1/version');if(r.ok)break;}catch{}if(proc.exitCode!==null)throw Error(log);await new Promise(r=>setTimeout(r,50));}assert(ready,log);const origin='http://127.0.0.1:'+ready.port;browser=await chromium.launch();const context=await browser.newContext();await context.addCookies([{name:'harness_session',value:ready.session,url:origin}]);const page=await context.newPage();page.setDefaultTimeout(8000);await page.addInitScript(version=>localStorage.setItem('tail-harness-tour-seen',version),(await fs.readFile(path.join(__dirname,'../agent_service/VERSION'),'utf8')).trim());await page.goto(origin);await page.locator('#startup-gate').waitFor({state:'hidden'});
const posts=[];page.on('request',r=>{if(r.method()==='POST'&&r.url()===origin+'/v1/jobs')posts.push(r.postDataJSON());});
await page.locator('#model-trigger').click();await page.locator('#model-menu details[data-provider="maestro"] summary').click();await page.getByRole('option',{name:/Maestro \(auto plan\)/}).click();await page.locator('#prompt').fill('/reviewer');await page.getByRole('option',{name:/reviewer/}).waitFor();await page.keyboard.press('Escape');await page.locator('#panel-toggle').click();await page.waitForFunction(()=>document.querySelector('#workspace-resources')?.textContent.includes('reviewer'));assert(!(await page.locator('#workspace-resources').innerText()).includes("Couldn't"));await page.locator('#panel-toggle').click();await page.locator('#prompt').fill('Plan a synthetic evidence review');await page.locator('#send').click();await page.locator('.maestro-plan-card[data-state="pending"]').waitFor();assert.equal(posts.at(-1).backend,'maestro');
const cid=await page.evaluate(()=>conversation),response=await page.request.get(origin+'/v1/conversations/'+cid),turn=(await response.json()).turns.at(-1);assert.equal(turn.gates[0].state,'pending');assert.equal(turn.state,'running');assert.deepEqual(JSON.parse(await fs.readFile(path.join(folder,'inference.json'))),['plan']);const before=await page.request.get(origin+'/v1/jobs/'+turn.id+'/spans');assert(!(await before.json()).spans.some(s=>s.name==='maestro_step'));
await page.reload();await page.locator('.maestro-plan-card[data-state="pending"]').waitFor();await page.waitForTimeout(300);assert.equal(await page.locator('#status').innerText(),'Waiting for plan approval');await page.getByRole('button',{name:'Edit plan in Run console',exact:true}).click();
const prose='Review the "public" report, Sophia\'s notes\nand Unicode 🐈';
const approvalPosts=[];page.on('request',r=>{if(r.method()==='POST'&&r.url().includes('/v1/approvals/'))approvalPosts.push(r.postDataJSON());});
const task=page.getByLabel('Task for step 1',{exact:true});await task.fill('');
await page.locator('.run-plan-actions button').filter({hasText:'Run with edits'}).click();
assert.equal(approvalPosts.length,0);await page.waitForFunction(id=>{const current=document.getElementById(id);return current?.isConnected&&current===document.activeElement;},await task.getAttribute('id'));assert.match(await page.locator('.run-plan-approval [role=status]').innerText(),/Enter a task for step 1/);
const stillPending=await page.request.get(origin+'/v1/conversations/'+cid);assert.equal((await stillPending.json()).turns.at(-1).gates[0].state,'pending');assert.deepEqual(JSON.parse(await fs.readFile(path.join(folder,'inference.json'))),['plan']);
await task.fill(prose);
await page.locator('.run-plan-actions button').filter({hasText:'Run with edits'}).click();await page.waitForFunction(()=>document.querySelector('.maestro-plan-card .state-pill')?.textContent.includes('Completed'));assert((await page.locator('#messages').innerText()).includes('Synthetic review complete'));assert.deepEqual(JSON.parse(await fs.readFile(path.join(folder,'inference.json'))),['plan','1']);assert.equal(approvalPosts.length,1);const approved=await page.request.get(origin+'/v1/conversations/'+cid);assert.equal((await approved.json()).turns.at(-1).gates[0].plan.steps[0].task,prose);
await page.locator('#new').click();await page.locator('#model-trigger').click();if(!(await page.locator('#model-menu details[data-provider="codex"]').evaluate(n=>n.open)))await page.locator('#model-menu details[data-provider="codex"] summary').click();await page.locator('#model-menu details[data-provider="codex"] [role=option]').first().click();await page.locator('#prompt').fill('Direct synthetic question');await page.locator('#send').click();await page.waitForFunction(()=>!submitting&&!busy);assert.equal(posts.at(-1).backend,'codex');assert.equal(await page.locator('.maestro-plan-card').count(),0);
await page.locator('#new').click();await page.locator('#prompt').fill('/maestro');await page.getByRole('option',{name:/maestro.*Generate a plan/i}).click();assert.equal(await page.locator('#model').inputValue(),'auto');await page.locator('#prompt').fill('/reviewer');await page.getByRole('option',{name:/reviewer/}).click();assert.equal(await page.locator('.resource-chip').count(),1);await page.locator('#prompt').fill('/reviewer inspect');await page.locator('#send').click();await page.waitForFunction(()=>!submitting&&!busy);assert((await page.locator('#messages').innerText()).includes('Synthetic review complete'));console.log('PASS Maestro visible entry, durable plan review, approval, direct chat and slash shortcut');
}finally{if(browser)await browser.close();proc.kill('SIGTERM');await new Promise(resolve=>{if(proc.exitCode!==null)return resolve();proc.once('exit',resolve);setTimeout(()=>proc.kill('SIGKILL'),2000).unref();});await fs.rm(folder,{recursive:true,force:true});}
})().catch(e=>{console.error(e);process.exitCode=1;});
