// Round-four synthetic browser regressions: actual rendering, keyboard and network boundaries.
const { chromium } = require(process.env.PLAYWRIGHT_MODULE || 'playwright');
const assert = require('node:assert/strict');
const fs = require('node:fs/promises');
const path = require('node:path');
async function capture(page, name) { if (!process.env.EVAL_OUTPUT) return; const folder = path.join(process.env.EVAL_OUTPUT, 'round4'); await fs.mkdir(folder, { recursive: true }); await page.screenshot({ path: path.join(folder, name + '.png') }); }
const { mount, run, span } = require('./run-console-fixture.cjs');
const resource = { id: 'project/p/reviewer', resource_id: 'project/p/reviewer', revision: '1', name: 'reviewer', kind: 'agent', mode: 'delegated', scope: 'project', origin: 'codex', selectable: true };
const plan = { steps: [{ role: 'Reviewer', backend: 'codex', model: 'fixture-model-with-a-long-identity', effort: 'configured', task: 'Review synthetic report' }] };
async function fixture(browser, width = 1024, height = 768) {
  const page = await browser.newPage({ viewport: { width, height } });
  page.setDefaultTimeout(4000);
  await page.addInitScript(() => localStorage.setItem('activity-open', '1'));
  const state = { delay: null, running: false, plan: false, checkpointCount: 0, inbox: [], jobs: [], conflict: false, posts: [], approvalResponse: null };
  const turn = id => ({ id: id + '-job', project: 'p', state: state.running ? 'running' : 'failed', workflow_checkpoint: true, workflow_completed_steps: state.checkpointCount, gates: state.plan ? [{ gate_id: 'plan', kind: 'maestro_plan', state: 'pending', plan }] : [], request: { prompt: 'Review ' + id, backend: 'codex', model: 'fixture-model', effort: 'configured', execution_mode: 'native' }, result: state.running ? null : { answer: 'Synthetic answer', error: 'fixture' } });
  await mount(page, async (url, request) => {
    if (request.method() === 'POST') { if (state.conflict) return {status:409,json:{code:'gate_already_resolved'}}; state.posts.push({ path: url.pathname, data: request.postDataJSON() }); if (state.approvalResponse) await state.approvalResponse; return { status: state.approvalResponse ? 200 : 422, json: state.approvalResponse ? {resolved:true} : {error:'synthetic_stop'} }; }
    if (url.pathname === '/v1/projects') return { json: { projects: ['p', 'q'], details: { p: { label: 'Project P' }, q: { label: 'Project Q' } } } };
    if (url.pathname === '/v1/models') return { json: { models: [{ id: 'fixture-model', backend: 'codex', efforts: ['configured'] }], providers: { codex: true } } };
    if (url.pathname === '/v1/resources') return { json: { items: [resource], warnings: [] } };
    if (url.pathname === '/v1/activity') return { json: { counts: { running: 1 }, jobs: [...state.jobs, { ...run, job_id: 'a-job', conversation_id: 'a', project_id: 'p', backend: 'codex', wait_reason: 'human_approval' }], needs_you: state.inbox.length ? state.inbox : state.plan ? [{ job_id:'a-job', conversation_id:'a', gate_id:'plan', kind:'maestro_plan', plan }] : [], providers: [] } };
    if (url.pathname === '/v1/conversations') return { json: { conversations: ['a','b'].map(id => ({ id, title: id.toUpperCase() + ' report', state: 'failed', project: 'p', last_job_id: id + '-job' })) } };
    if (/^\/v1\/conversations\/(a|b|child)$/.test(url.pathname)) {
      if (state.delay) await state.delay;
      const id = url.pathname.split('/').at(-1);
      return { json: { title: id.toUpperCase() + ' report', turns: [turn(id)] } };
    }
    if (url.pathname.endsWith('/cancel')) { state.running = false; return { json: { cancelled: true } }; }
    if (/^\/v1\/jobs\/.*-job$/.test(url.pathname)) return { json: turn(url.pathname.split('/').at(-1).replace('-job','')) };
    if (url.pathname.endsWith('/spans')) return { json: { spans: ['Planner', 'Accessibility and interaction reviewer', 'Implementation and integration engineer'].map((name, i) => ({ ...span, start_ts: Date.now()/1000-12, name, span_id: 'span-' + i, attrs: { ...span.attrs, 'gen_ai.provider.name': 'codex', 'gen_ai.request.model': 'fixture-model', effort: 'medium' } })) } };
    if (url.pathname === '/v1/project-files') return {json:{state:'ready',root_id:'home', path:url.searchParams.get('path')||'', roots:[{id:'home',label:'Local Folders'}], entries:url.searchParams.get('path')?[]:[{name:'examples',path:'examples',type:'directory'}]}};
    if (url.pathname.endsWith('/events')) return { body: '', contentType: 'text/event-stream' };
  });
  async function open(id) { if (width <= 620) await page.locator('#menu').click(); await page.locator('#sidebar .conversation-row > button').filter({ hasText: id.toUpperCase() + ' report' }).click(); await page.waitForFunction(title => !loading && document.querySelector('#conversation-title').textContent === title, id.toUpperCase() + ' report'); }
  return { page, open, state };
}
const hit = locator => locator.evaluate(node => { const r = node.getBoundingClientRect(); const h = document.elementFromPoint(r.x + r.width / 2, r.y + r.height / 2); return h === node || node.contains(h); });
const settle = page => page.evaluate(() => Promise.all(document.getAnimations().filter(a => a.effect?.getTiming().iterations !== Infinity).map(a => a.finished.catch(() => {}))));

const question = (id='question', multi=false) => ({gate_id:id,job_id:'a-job',conversation_id:'a',project_id:'p',kind:'gate',question:'Choose report format',multi_select:multi,options:[{id:'brief',label:'Brief summary',description:'Excludes individual records'},{id:'detailed',label:'Detailed report',description:'Includes each record and supporting notes'}]});
(async () => {
 const browser=await chromium.launch(), failures=[];
 async function check(name,fn){if(process.env.ONLY&&!process.env.ONLY.split(',').some(id=>name.startsWith(id)))return;try{await fn();console.log('PASS '+name);}catch(e){failures.push(name+': '+e.stack);console.error('FAIL '+name+': '+e.message);}}
 async function inbox(page, filter='request'){await page.locator('#attention-bell').click();await page.locator('[data-attention-filter="'+filter+'"]').focus();await page.keyboard.press('Enter');await page.locator('#needs-you-inbox').waitFor();}
 try {
 await check('A1-F1 complete cards and decisions fit without scrolling', async()=>{
  for(const [width,height] of [[1440,900],[1280,720],[1024,768],[400,812]]) for(const theme of ['porcelain','amethyst','petroleum']){
   const {page,state,open}=await fixture(browser,width,height);state.plan=true;state.running=true;await page.evaluate(theme=>HarnessTheme.apply(theme),theme);await open('a');await page.evaluate(()=>runConsole.openRun('a-job'));await page.locator('.run-span-row').nth(2).waitFor();await settle(page);const originalHeight=(await page.locator('#run-console').boundingBox()).height;
   for(const mode of ['default','max','restore']){
    if(width>700&&mode!=='default')await page.locator('#run-console-maximize').click();
    const geometry=await page.evaluate(()=>{const body=document.querySelector('.run-console-body'),bounds=body.getBoundingClientRect();return {scroll:body.scrollTop,limit:bounds.bottom,items:[...body.querySelectorAll('.run-span-row,.run-plan-actions')].map(n=>({text:n.textContent,top:n.getBoundingClientRect().top,bottom:n.getBoundingClientRect().bottom})),buttons:[...body.querySelectorAll('.run-plan-actions button')].map(n=>{const r=n.getBoundingClientRect();return {text:n.textContent,hit:n.contains(document.elementFromPoint(r.x+r.width/2,r.y+r.height/2))};})};});
    assert.equal(geometry.scroll,0);assert.equal(geometry.items.length,4);assert(geometry.items.every(r=>r.bottom<=geometry.limit),width+' '+theme+' '+mode+' '+JSON.stringify(geometry));assert(geometry.buttons.every(b=>b.hit),JSON.stringify(geometry));if(mode==='restore')assert.equal((await page.locator('#run-console').boundingBox()).height,originalHeight);await capture(page,`pipeline-${width}-${theme}-${mode}`);
   }await page.close();
  }
 });
 await check('A1-F1 pending plan respects explicit keyboard resizing', async()=>{const {page,state,open}=await fixture(browser,1280,720);state.plan=true;state.running=true;await open('a');await page.evaluate(()=>runConsole.openRun('a-job'));await page.locator('.run-span-row').nth(2).waitFor();await settle(page);const before=(await page.locator('#run-console').boundingBox()).height;await page.locator('#run-console-resize').focus();await page.keyboard.press('ArrowDown');const after=(await page.locator('#run-console').boundingBox()).height;assert(after<before);await page.waitForTimeout(2200);assert.equal((await page.locator('#run-console').boundingBox()).height,after);await page.close();});
 await check('A1-F1 telemetry preserves horizontally inspected cards',async()=>{const {page,state,open}=await fixture(browser,1024,768);await page.evaluate(()=>{sizePanel('sidebar',300);sizePanel('activity-panel',390);});state.plan=true;state.running=true;await open('a');await page.evaluate(()=>runConsole.openRun('a-job'));await page.locator('.run-span-row').nth(2).waitFor();await page.locator('.run-span-list').evaluate(n=>n.scrollLeft=185);assert.equal(await page.locator('.run-span-list').evaluate(n=>n.scrollLeft),185);await page.waitForTimeout(4300);const view=await page.evaluate(()=>{const list=document.querySelector('.run-span-list'),node=list.querySelectorAll('.run-span-tokens')[1],r=node.getBoundingClientRect();return {scroll:list.scrollLeft,hit:node.contains(document.elementFromPoint(r.x+r.width/2,r.y+r.height/2))};});assert.equal(view.scroll,185);assert(view.hit,JSON.stringify(view));await page.close();});
 await check('A1-F2 readable waits in sidebar and Runs',async()=>{const {page,state,open}=await fixture(browser,1440,900);state.running=true;state.jobs=[{...run,job_id:'child',state:'queued',wait_reason:'conversation_parent'}];await open('a');await page.waitForFunction(()=>document.querySelector('.conversation-summary').textContent.includes('Waiting'));assert.equal(await page.locator('.conversation-summary').first().innerText(),'Waiting for your approval');await page.evaluate(()=>runConsole.openRun('a-job'));await page.getByRole('tab',{name:'Runs',exact:true}).click();const text=await page.locator('.run-console-body').innerText();assert.match(text,/Waiting for the previous response/);assert(!text.includes('human_approval'));assert.equal(await page.evaluate(()=>conversationSummary({wait_reason:'Provider busy'})),'Provider busy');await page.close();});
 await check('A2-F1 storage recovery flushes newest draft before reload',async()=>{const {page}=await fixture(browser);await page.fill('#prompt','Saved before quota');const errors=await page.evaluate(()=>{let failures=0;for(const size of [262144,32768,4096,512,64,1]){for(let i=0;i<10000;i++){try{sessionStorage.setItem('quota-'+size+'-'+i,'x'.repeat(size));}catch{failures++;break;}}}return failures;});assert(errors>0);await page.fill('#prompt','/reviewer');await page.locator('#resource-menu [data-resource-id="project/p/reviewer"]').click();await page.keyboard.type(' Newest valuable draft requiring preservation');const exact=await page.inputValue('#prompt');assert.match(await page.locator('#draft-storage-warning').innerText(),/not saved|only in this tab/i);await page.evaluate(()=>{for(const key of Object.keys(sessionStorage))if(key.startsWith('quota-'))sessionStorage.removeItem(key);});await page.reload();await page.locator('#startup-gate').waitFor({state:'hidden'});assert.equal(await page.inputValue('#prompt'),exact);assert.equal(await page.locator('.resource-chip').count(),1);await page.close();});
 await check('A2-F2 console to side panels preserves visible focus',async()=>{for(const toggle of ['menu','panel-toggle']){const {page}=await fixture(browser,400,812);await page.keyboard.press('Control+j');await page.locator('#'+toggle).click();await settle(page);assert(await hit(page.locator(':focus')));assert.equal(await page.locator('[aria-modal="true"]:visible').count(),1);for(const key of ['Shift+Tab','Tab','Escape']){await page.keyboard.press(key);await settle(page);assert(await hit(page.locator(':focus')),key+' '+await page.locator(':focus').evaluate(n=>n.outerHTML));}await page.close();}});
 await check('A2-F3 resume tracking transfers focus to composer',async()=>{const {page,state,open}=await fixture(browser);state.running=true;await open('a');await page.fill('#prompt','Preserved draft');await page.route('**/v1/jobs/a-job/events',route=>route.fulfill({status:503,json:{error:'synthetic_network'}}));await page.evaluate(()=>watch(3));await page.locator('#resume-execution').waitFor();await page.route('**/v1/jobs/a-job/events',route=>route.fulfill({body:'id: 301\nevent: answer_delta\ndata: {"text":"Recovered event"}\n\n',contentType:'text/event-stream'}));await page.locator('#resume-execution').focus();await page.keyboard.press('Enter');await page.waitForTimeout(100);assert.equal(await page.locator(':focus').getAttribute('id'),'prompt');assert(await hit(page.locator(':focus')));assert.equal(await page.inputValue('#prompt'),'Preserved draft');await page.close();});
 await check('A2-F4 folder expansion has 24px pointer targets',async()=>{for(const width of [1440,400]){const {page}=await fixture(browser,width,812);if(width<1000)await page.locator('#panel-toggle').click();const folder=page.getByRole('button',{name:'Expand examples',exact:true}).first();await folder.waitFor();await folder.scrollIntoViewIfNeeded();const box=await folder.boundingBox();assert(box.width>=24&&box.height>=24,JSON.stringify(box));assert(await folder.evaluate(n=>{const r=n.getBoundingClientRect();return [r.left+1,r.right-1].every(x=>n.contains(document.elementFromPoint(x,r.y+r.height/2)));}));await folder.click();await page.getByRole('button',{name:'Collapse examples',exact:true}).first().waitFor();await page.close();}});
 await check('A2-F5 responsive console semantics and background exclusion',async()=>{const {page}=await fixture(browser,400,812);await page.keyboard.press('Control+j');const dialog=page.getByRole('dialog',{name:'Run console',exact:true});await dialog.waitFor();assert.equal(await dialog.getAttribute('aria-modal'),'true');const ax=await page.context().newCDPSession(page);const tree=await ax.send('Accessibility.getFullAXTree');assert(!tree.nodes.some(n=>!n.ignored&&n.role?.value==='combobox'&&n.name?.value==='Message'));assert(await page.locator('#prompt').evaluate(n=>!!n.closest('[inert]')));await page.setViewportSize({width:1440,height:900});await page.getByRole('region',{name:'Run console',exact:true}).waitFor();assert.equal(await page.getByRole('combobox',{name:'Message',exact:true}).count(),1);assert(!(await page.locator('#prompt').evaluate(n=>!!n.closest('[inert]'))));await page.setViewportSize({width:400,height:812});await page.getByRole('dialog',{name:'Run console',exact:true}).waitFor();assert(await hit(page.locator(':focus')));await page.close();});
 await check('A2-F6 inbox returns to its actual opener',async()=>{const {page}=await fixture(browser,1440,900);for(const source of ['attention-bell','needs-you-toggle'])for(const close of ['Escape','button']){await page.locator('#'+source).click();if(source==='attention-bell')await page.locator('#attention-open-inbox').click();await page.locator('#needs-you-inbox').waitFor();if(close==='Escape')await page.keyboard.press('Escape');else await page.getByRole('button',{name:'Close inbox',exact:true}).click();await page.waitForTimeout(100);assert.equal(await page.locator(':focus').getAttribute('id'),source);}await page.close();});
 await check('A5-F1 conflicting gate answers never confirm losing selection',async()=>{for(const multi of [false,true]){const {page,state,open}=await fixture(browser);await open('a');const q=question('race',multi);await page.evaluate(q=>showGate(q),q);state.conflict=true;await page.locator('#gate-race input[value="detailed"]').check();await page.getByRole('button',{name:'Confirm choice',exact:true}).click();await page.waitForFunction(()=>document.querySelector('#gate-race').dataset.state==='resolved');assert.equal(await page.locator('#gate-race input:checked').count(),0);assert.match(await page.locator('#gate-race [role="status"]').innerText(),/another session|reload.*answer|not available/i);await page.evaluate(()=>finishGate('race','resolved',{choice:'brief'}));assert.equal(await page.locator('#gate-race input:checked').inputValue(),'brief');await page.close();}});
 await check('A5-F2 switching inbox filters rebuilds pending questions',async()=>{const {page,state}=await fixture(browser,1440,900);state.inbox=[question()];state.jobs=[{...run,job_id:'done',state:'completed'},{...run,job_id:'failed',state:'failed'}];for(const filter of ['request','complete','request','error','request']){await inbox(page,filter);if(filter==='request'){await page.locator('[data-request-id="question"] input').first().waitFor();assert.equal(await page.locator('#needs-you-inbox input').count(),2);await page.locator('#needs-you-inbox input[value="brief"]').check();assert(await page.getByRole('button',{name:'Submit answer',exact:true}).isEnabled());}else await page.getByRole('button',{name:'View run',exact:true}).waitFor();await page.keyboard.press('Escape');}await page.close();});
 await check('A5-F3 inbox exposes ordered plan execution details',async()=>{for(const width of [1440,400]){const {page,state}=await fixture(browser,width,812);state.inbox=[{...question('plan'),approval_kind:'maestro_plan',plan,options:[{id:'approve',label:'Approve plan & run'},{id:'discard',label:'Discard plan'}]}];await inbox(page);const card=page.locator('[data-request-id="plan"]');await card.waitFor();const text=await card.innerText();for(const expected of ['Reviewer','Review synthetic report','codex','fixture-model-with-a-long-identity','configured'])assert(text.includes(expected),text);assert.equal(await card.locator('ol li').count(),1);await page.close();}});
 await check('A5-F4 inbox preserves option descriptions and association',async()=>{const {page,state}=await fixture(browser,1440,900);state.inbox=[question('single'),question('multi',true)];await inbox(page);for(const id of ['single','multi']){const card=page.locator('[data-request-id="'+id+'"]');await card.waitFor();assert.match(await card.innerText(),/Excludes individual records/);assert.match(await card.innerText(),/Includes each record/);const input=card.locator('input[value="brief"]');const description=await input.getAttribute('aria-describedby');assert(description);assert.equal(await page.locator('#'+description).innerText(),'Excludes individual records');}await page.close();});
 await check('A5-F6 attention actions receive pointer hits above resize handles',async()=>{const {page}=await fixture(browser,1440,900);for(const width of [390,340]){await page.evaluate(w=>document.documentElement.style.setProperty('--th-activity-width',w+'px'),width);for(const filter of ['request','complete','error']){await page.locator('#attention-bell').click();const target=page.locator('[data-attention-filter="'+filter+'"]');assert(await target.evaluate(n=>{const r=n.getBoundingClientRect();return [r.x+1,r.x+r.width/2,r.right-1].every(x=>n.contains(document.elementFromPoint(x,r.y+r.height/2)));}));await target.click();await page.locator('#needs-you-inbox').waitFor();await page.keyboard.press('Escape');}}await page.close();});
 } finally {await browser.close();}
 if(failures.length){console.error(failures.join('\n'));process.exitCode=1;}
})();
