// Round-eight synthetic browser regressions: actual rendering, keyboard and network boundaries.
const { chromium } = require(process.env.PLAYWRIGHT_MODULE || 'playwright');
const assert = require('node:assert/strict');
const fs = require('node:fs/promises');
const path = require('node:path');
async function capture(page, name) { if (!process.env.EVAL_OUTPUT) return; const folder = path.join(process.env.EVAL_OUTPUT, 'round8'); await fs.mkdir(folder, { recursive: true }); await page.screenshot({ path: path.join(folder, name + '.png') }); }
const { mount, run, span } = require('./run-console-fixture.cjs');
const resource = { id: 'project/p/reviewer', resource_id: 'project/p/reviewer', revision: '1', name: 'reviewer', kind: 'agent', mode: 'delegated', scope: 'project', origin: 'codex', selectable: true };
const plan = { steps: [{ role: 'Reviewer', backend: 'codex', model: 'synthetic-model-family-with-extended-context-and-reasoning', effort: 'configured', task: 'Review synthetic report' }] };
async function fixture(browser, width = 1024, height = 768) {
  const page = await browser.newPage({ viewport: { width, height } });
  page.setDefaultTimeout(4000);
  const state = { spanVersion: 0, failNavigation: false, emptySpans: false, resourceDelay: null, rootDelay: null, roots: false, usage: null, gate: null, resources: null, maestro: false, completed: false, delay: null, running: false, plan: false, checkpointCount: 0, inbox: [], jobs: [], conflict: false, posts: [], approvalResponse: null, successfulSend: false, missingSource: false, pendingEvents: false };
  const turn = id => ({ id: id + '-job', project: id === 'b' ? 'q' : 'p', state: state.running ? 'running' : state.completed ? 'completed' : 'failed', workflow_checkpoint: true, workflow_completed_steps: state.checkpointCount, gates: state.gate ? [state.gate] : state.plan ? [{ gate_id: 'plan', kind: 'maestro_plan', state: 'pending', plan }] : [], request: { prompt: 'Review ' + id, backend: 'codex', model: 'fixture-model', effort: 'configured', execution_mode: 'native' }, result: state.running ? null : { answer: 'Synthetic answer', ...(state.completed ? {} : {error:'fixture'}), ...(state.usage ? {metrics:state.usage} : {}) } });
  await mount(page, async (url, request) => {
    if (request.method() === 'POST' && state.missingSource && url.pathname.endsWith('/resume')) return {status:422,json:{code:'workflow_source_unavailable'}};
    if (request.method() === 'POST' && state.successfulSend && url.pathname === '/v1/jobs') { state.posts.push({path:url.pathname,data:request.postDataJSON()}); return {json:{job_id:'child'}}; }
    if (request.method() === 'POST') { if (state.conflict) return {status:409,json:{code:'gate_already_resolved'}}; state.posts.push({ path: url.pathname, data: request.postDataJSON() }); if (state.approvalResponse) await state.approvalResponse; return { status: state.approvalResponse ? 200 : 422, json: state.approvalResponse ? {resolved:true} : {error:'synthetic_stop'} }; }
    if (url.pathname === '/v1/projects') return { json: { projects: ['p', 'q'], details: { p: { label: 'Synthetic review project' }, q: { label: 'Project Q' } } } };
    if (url.pathname === '/v1/models') return { json: { models: [{ id: 'fixture-model', backend: 'codex', efforts: ['configured'] }, { id: plan.steps[0].model, backend: 'codex', efforts: ['configured'] }], maestro: state.maestro, providers: { codex: true } } };
    if (url.pathname === '/v1/resources' && url.searchParams.get('project_id') === 'p' && state.resourceDelay) await state.resourceDelay;
    if (url.pathname === '/v1/resources') return { json: { items: state.resources || [{...resource,name:'reviewer-' + url.searchParams.get('project_id')}], warnings: [] } };
    if (url.pathname === '/v1/activity') return { json: { counts: { running: 1 }, jobs: [...state.jobs, { ...run, job_id: 'a-job', conversation_id: 'a', project_id: 'p', backend: 'codex', wait_reason: 'human_approval' }], needs_you: state.inbox.length ? state.inbox : state.plan ? [{ job_id:'a-job', conversation_id:'a', gate_id:'plan', kind:'maestro_plan', options:[{id:'approve',label:'Approve'},{id:'deny',label:'Discard'}], plan }] : [], providers: [] } };
    if (url.pathname === '/v1/conversations') return { json: { conversations: ['a','b'].map(id => ({ id, title: id.toUpperCase() + ' report', state: 'failed', backend:'codex', model:'fixture-model', project: 'p', last_job_id: id + '-job' })) } };
    if (/^\/v1\/conversations\/(a|b|child)$/.test(url.pathname)) {
      if (state.failNavigation && url.pathname.endsWith('/b')) return {status:503,json:{code:'unavailable'}};
      if (state.delay) await state.delay;
      const id = url.pathname.split('/').at(-1);
      return { json: { title: id.toUpperCase() + ' report', turns: [turn(id)] } };
    }
    if (url.pathname.endsWith('/cancel')) { state.running = false; return { json: { cancelled: true } }; }
    if (/^\/v1\/jobs\/.*-job$/.test(url.pathname)) return { json: turn(url.pathname.split('/').at(-1).replace('-job','')) };
    if (url.pathname.endsWith('/spans') && state.emptySpans) return {json:{spans:[]}};
    if (url.pathname.endsWith('/spans')) return { json: { spans: ['Planner', 'Accessibility and interaction reviewer', 'Implementation and integration engineer'].map((name, i) => ({ ...span, start_ts: 10 + i, end_ts: 20 + i, name: name + state.spanVersion, span_id: 'span-' + i, attrs: { ...span.attrs, 'gen_ai.provider.name': 'codex', 'gen_ai.request.model': 'fixture-model', effort: 'medium', enforcement:'unenforced', advisory:true } })) } };
    if (url.pathname === '/v1/project-files' && url.searchParams.get('project_id') === 'p' && state.rootDelay) await state.rootDelay;
    if (url.pathname === '/v1/project-files' && url.searchParams.get('view') === 'authorized') return {json:{state:'ready',roots:state.roots?[{id:'root',path:'/synthetic/' + url.searchParams.get('project_id')}]:[]}};
    if (url.pathname === '/v1/project-files') return {json:{state:'ready',root_id:'home', path:url.searchParams.get('path')||'', roots:[{id:'home',label:'Local Folders'}], entries:url.searchParams.get('path')?[]:[{name:'examples',path:'examples',type:'directory'}]}};
    if (url.pathname.endsWith('/events') && state.pendingEvents) await new Promise(()=>{});
    if (url.pathname.endsWith('/events')) return { body: '', contentType: 'text/event-stream' };
  });
  async function open(id) { if (width <= 620) await page.locator('#menu').click(); await page.locator('#history .conversation-row > button').filter({ hasText: id.toUpperCase() + ' report' }).click(); await page.waitForFunction(title => !loading && document.querySelector('#conversation-title').textContent === title, id.toUpperCase() + ' report'); }
  return { page, open, state };
}
const hit = locator => locator.evaluate(node => { const r = node.getBoundingClientRect(); const h = document.elementFromPoint(r.x + r.width / 2, r.y + r.height / 2); return h === node || node.contains(h); });
const settle = page => page.evaluate(() => Promise.all(document.getAnimations().filter(a => a.effect?.getTiming().iterations !== Infinity).map(a => a.finished.catch(() => {}))));


(async () => {
 const browser=await chromium.launch(), failures=[];
 async function check(name, fn) {if(process.env.ONLY&&!process.env.ONLY.split(',').some(id=>name.startsWith(id)))return;try{await fn();console.log('PASS '+name);}catch(e){failures.push(name+': '+e.stack);console.error('FAIL '+name+': '+e.message);}}
 try {
 await check('A1-F1 clipped inline identity disclosure',async()=>{
  for(const theme of ['porcelain','amethyst','petroleum']){const f=await fixture(browser,400,812),p=f.page;f.state.plan=true;f.state.running=true;await f.open('a');await p.evaluate(t=>TailTheme.apply(t),theme);const chip=p.locator('.maestro-plan-card .backend-chip').first();const g=await chip.evaluate(n=>({client:n.clientWidth,scroll:n.scrollWidth,text:n.textContent,title:n.title}));assert(g.scroll>g.client);await chip.hover();assert(await hit(chip));assert.equal(g.title,g.text);await capture(p,'identity-'+theme);await p.close();}
 });
 await check('A2-F1 failed navigation offers live recovery',async()=>{const f=await fixture(browser),p=f.page;f.state.running=true;f.state.pendingEvents=true;await f.open('a');await p.waitForFunction(()=>!!controller);await p.locator('#prompt').fill('Exact retained draft');f.state.failNavigation=true;await f.open('b').catch(()=>{});await p.waitForFunction(()=>!loading);assert.equal(await p.locator('#prompt').inputValue(),'Exact retained draft');assert(await p.evaluate(()=>!!controller || streamDisconnected));const resume=p.getByRole('button',{name:'Resume tracking',exact:true});if(await resume.isVisible()){await resume.focus();assert(await hit(resume));}await p.close();});
 await check('A2-F1 failed navigation from terminal run does not offer Resume',async()=>{const f=await fixture(browser),p=f.page;f.state.completed=true;await f.open('a');await p.evaluate(()=>watch());await p.waitForFunction(()=>!busy);assert(await p.evaluate(()=>!!controller));f.state.failNavigation=true;await p.locator('#history .conversation-row > button').filter({hasText:'B report'}).click();await p.waitForFunction(()=>!loading);assert(await p.locator('#resume-execution').isHidden());assert(!(await p.evaluate(()=>streamDisconnected)));await p.close();});
 await check('A2-F2 selected available option accepts Tab and Enter',async()=>{for(const key of ['Tab','Enter']){const f=await fixture(browser),p=f.page;f.state.resources=[{...resource,id:'disabled',name:'a-disabled',selectable:false,unavailable_reason:'Unavailable'},{...resource,id:'enabled',name:'b-enabled'}];await p.locator('#prompt').fill('/');await p.locator('#resource-menu [aria-selected=true]').waitFor();const chosen=await p.locator('#resource-menu [aria-selected=true]').innerText();assert(chosen.includes('b-enabled'));await p.locator('#prompt').press(key);assert.equal(await p.locator('.resource-chip').count(),1);assert((await p.locator('.resource-chip').innerText()).includes('b-enabled'));await p.close();}});
 await check('A2-F2 unavailable option permits forward traversal',async()=>{const f=await fixture(browser),p=f.page;f.state.resources=[{...resource,id:'disabled',name:'a-disabled',selectable:false,unavailable_reason:'Unavailable'}];await p.locator('#prompt').fill('/');const option=p.locator('#resource-menu [aria-disabled=true]').first();await option.waitFor();await option.focus();await p.keyboard.press('Tab');assert(!(await p.evaluate(()=>document.activeElement?.getAttribute('aria-disabled')==='true')));assert(!(await p.locator('#resource-menu').evaluate(n=>n.matches(':popover-open'))));assert.equal(await p.locator('.resource-chip').count(),0);await p.close();});
 await check('A2-F3 polling preserves plan editor focus selection and scroll',async()=>{const f=await fixture(browser),p=f.page;f.state.plan=true;f.state.running=true;await f.open('a');await p.evaluate(()=>runConsole.openRun('a-job'));await p.locator('#run-plan-edit').click();const editor=p.getByRole('textbox',{name:'Task for step 1'});const draft='Exact Unicode draft 🐈\n'+('line\n'.repeat(80));await editor.fill(draft);await editor.evaluate(n=>{n.focus();n.setSelectionRange(12,18,'backward');n.scrollTop=65;});const oldScroll=await editor.evaluate(n=>n.scrollTop);f.state.spanVersion++;await p.waitForTimeout(4500);assert.deepEqual(await editor.evaluate(n=>({focus:n===document.activeElement,start:n.selectionStart,end:n.selectionEnd,direction:n.selectionDirection,text:n.value,scroll:n.scrollTop})),{focus:true,start:12,end:18,direction:'backward',text:draft,scroll:oldScroll});assert(await hit(editor));await p.close();});
 await check('A2-F4 pending decisions survive changed-span polling',async()=>{for(const choice of ['approve','deny']){const f=await fixture(browser),p=f.page;f.state.plan=true;f.state.running=true;let release;f.state.approvalResponse=new Promise(r=>release=r);await f.open('a');await p.evaluate(()=>runConsole.openRun('a-job'));const bar=p.locator('.run-plan-approval'),action=bar.getByRole('button',{name:choice==='approve'?'✓ Approve plan & run':'Discard',exact:true});await action.focus();await p.keyboard.press('Enter');await p.waitForTimeout(100);f.state.spanVersion++;await p.waitForTimeout(4500);assert(await action.isDisabled());assert(await bar.getByRole('button',{name:choice==='approve'?'Discard':'✓ Approve plan & run',exact:true}).isDisabled());assert((await bar.getByRole('status').innerText()).includes(choice==='approve'?'Approving':'Discarding'));await p.keyboard.press('Enter');assert.equal(f.state.posts.length,1);release();await p.close();}});
 await check('A2-F5 gate drafts survive reload and terminal authority',async()=>{for(const multi of [false,true]){const f=await fixture(browser,400,812),p=f.page;f.state.gate={gate_id:'choice',kind:'options',question:'Audience?',multi_select:multi,state:'pending',options:[{id:'staff',label:'Staff'},{id:'public',label:'Public'}]};f.state.running=true;await f.open('a');await p.getByLabel('Staff',{exact:true}).check();if(multi)await p.getByLabel('Public',{exact:true}).check();await p.locator('#prompt').fill('Saved draft');await p.reload();await p.getByLabel('Staff',{exact:true}).waitFor();assert(await p.getByLabel('Staff',{exact:true}).isChecked());if(multi)assert(await p.getByLabel('Public',{exact:true}).isChecked());assert(await p.getByRole('button',{name:'Confirm choice',exact:true}).isEnabled());f.state.gate={...f.state.gate,state:'resolved',choice:'public'};await p.reload();await p.getByLabel('Staff',{exact:true}).waitFor();assert(!(await p.getByLabel('Staff',{exact:true}).isChecked()));assert(await p.getByRole('button',{name:'Confirm choice',exact:true}).isDisabled());await p.close();}});
 await check('A5-F3 pending gate replay keeps waiting wording',async()=>{for(const publish of [false,true]){const f=await fixture(browser),p=f.page;f.state.gate={gate_id:'choice',kind:'options',question:'Audience?',state:'pending',publish,options:[{id:'staff',label:'Staff'}]};f.state.running=true;await f.open('a');await p.reload();await p.locator('#gate-choice').waitFor();assert((await p.locator('#status').innerText()).includes('Waiting'));assert((await p.locator('.message-activity summary').last().innerText()).includes('Waiting'));await p.close();}});
 await check('A5-F5 publication risk and evidence visible before deciding',async()=>{const f=await fixture(browser,400,812),p=f.page;f.state.gate={gate_id:'publish',kind:'options',question:'Publish?',state:'pending',publish:true,risk:'high',evidence:'Synthetic reviewed evidence',options:[{id:'approve',label:'Approve'},{id:'deny',label:'Deny'}]};f.state.running=true;await f.open('a');for(const reload of [false,true]){if(reload)await p.reload();const evidence=p.getByRole('region',{name:'Publication evidence',exact:true});await evidence.waitFor();assert((await evidence.innerText()).includes('Risk: high'));const line=evidence.getByText('Evidence: Synthetic reviewed evidence',{exact:true});await line.scrollIntoViewIfNeeded();assert(await hit(line));await capture(p,'publication-evidence');}await p.close();});
 } finally {await browser.close();}
 if(failures.length){console.error(failures.join('\n'));process.exitCode=1;}
})();
