// Round-six synthetic browser regressions: actual rendering, keyboard and network boundaries.
const { chromium } = require(process.env.PLAYWRIGHT_MODULE || 'playwright');
const assert = require('node:assert/strict');
const fs = require('node:fs/promises');
const path = require('node:path');
async function capture(page, name) { if (!process.env.EVAL_OUTPUT) return; const folder = path.join(process.env.EVAL_OUTPUT, 'round7'); await fs.mkdir(folder, { recursive: true }); await page.screenshot({ path: path.join(folder, name + '.png') }); }
const { mount, run, span } = require('./run-console-fixture.cjs');
const resource = { id: 'project/p/reviewer', resource_id: 'project/p/reviewer', revision: '1', name: 'reviewer', kind: 'agent', mode: 'delegated', scope: 'project', origin: 'codex', selectable: true };
const plan = { steps: [{ role: 'Reviewer', backend: 'codex', model: 'fixture-model-with-a-long-identity', effort: 'configured', task: 'Review synthetic report' }] };
async function fixture(browser, width = 1024, height = 768) {
  const page = await browser.newPage({ viewport: { width, height } });
  page.setDefaultTimeout(4000);
  const state = { emptySpans: false, resourceDelay: null, rootDelay: null, roots: false, usage: null, gate: null, resources: null, maestro: false, completed: false, delay: null, running: false, plan: false, checkpointCount: 0, inbox: [], jobs: [], conflict: false, posts: [], approvalResponse: null, successfulSend: false, missingSource: false, pendingEvents: false };
  const turn = id => ({ id: id + '-job', project: id === 'b' ? 'q' : 'p', state: state.running ? 'running' : state.completed ? 'completed' : 'failed', workflow_checkpoint: true, workflow_completed_steps: state.checkpointCount, gates: state.gate ? [state.gate] : state.plan ? [{ gate_id: 'plan', kind: 'maestro_plan', state: 'pending', plan }] : [], request: { prompt: 'Review ' + id, backend: 'codex', model: 'fixture-model', effort: 'configured', execution_mode: 'native' }, result: state.running ? null : { answer: 'Synthetic answer', ...(state.completed ? {} : {error:'fixture'}), ...(state.usage ? {metrics:state.usage} : {}) } });
  await mount(page, async (url, request) => {
    if (request.method() === 'POST' && state.missingSource && url.pathname.endsWith('/resume')) return {status:422,json:{code:'workflow_source_unavailable'}};
    if (request.method() === 'POST' && state.successfulSend && url.pathname === '/v1/jobs') { state.posts.push({path:url.pathname,data:request.postDataJSON()}); return {json:{job_id:'child'}}; }
    if (request.method() === 'POST') { if (state.conflict) return {status:409,json:{code:'gate_already_resolved'}}; state.posts.push({ path: url.pathname, data: request.postDataJSON() }); if (state.approvalResponse) await state.approvalResponse; return { status: state.approvalResponse ? 200 : 422, json: state.approvalResponse ? {resolved:true} : {error:'synthetic_stop'} }; }
    if (url.pathname === '/v1/projects') return { json: { projects: ['p', 'q'], details: { p: { label: 'Synthetic review project' }, q: { label: 'Project Q' } } } };
    if (url.pathname === '/v1/models') return { json: { models: [{ id: 'fixture-model', backend: 'codex', efforts: ['configured'] }], maestro: state.maestro, providers: { codex: true } } };
    if (url.pathname === '/v1/resources' && url.searchParams.get('project_id') === 'p' && state.resourceDelay) await state.resourceDelay;
    if (url.pathname === '/v1/resources') return { json: { items: state.resources || [{...resource,name:'reviewer-' + url.searchParams.get('project_id')}], warnings: [] } };
    if (url.pathname === '/v1/activity') return { json: { counts: { running: 1 }, jobs: [...state.jobs, { ...run, job_id: 'a-job', conversation_id: 'a', project_id: 'p', backend: 'codex', wait_reason: 'human_approval' }], needs_you: state.inbox.length ? state.inbox : state.plan ? [{ job_id:'a-job', conversation_id:'a', gate_id:'plan', kind:'maestro_plan', options:[{id:'approve',label:'Approve'},{id:'deny',label:'Discard'}], plan }] : [], providers: [] } };
    if (url.pathname === '/v1/conversations') return { json: { conversations: ['a','b'].map(id => ({ id, title: id.toUpperCase() + ' report', state: 'failed', backend:'codex', model:'fixture-model', project: 'p', last_job_id: id + '-job' })) } };
    if (/^\/v1\/conversations\/(a|b|child)$/.test(url.pathname)) {
      if (state.delay) await state.delay;
      const id = url.pathname.split('/').at(-1);
      return { json: { title: id.toUpperCase() + ' report', turns: [turn(id)] } };
    }
    if (url.pathname.endsWith('/cancel')) { state.running = false; return { json: { cancelled: true } }; }
    if (/^\/v1\/jobs\/.*-job$/.test(url.pathname)) return { json: turn(url.pathname.split('/').at(-1).replace('-job','')) };
    if (url.pathname.endsWith('/spans') && state.emptySpans) return {json:{spans:[]}};
    if (url.pathname.endsWith('/spans')) return { json: { spans: ['Planner', 'Accessibility and interaction reviewer', 'Implementation and integration engineer'].map((name, i) => ({ ...span, start_ts: 10 + i, end_ts: 20 + i, name, span_id: 'span-' + i, attrs: { ...span.attrs, 'gen_ai.provider.name': 'codex', 'gen_ai.request.model': 'fixture-model', effort: 'medium', enforcement:'unenforced', advisory:true } })) } };
    if (url.pathname === '/v1/project-files' && url.searchParams.get('project_id') === 'p' && state.rootDelay) await state.rootDelay;
    if (url.pathname === '/v1/project-files' && url.searchParams.get('view') === 'authorized') return {json:{state:'ready',roots:state.roots?[{id:'root',path:'/synthetic/' + url.searchParams.get('project_id')}]:[]}};
    if (url.pathname === '/v1/project-files') return {json:{state:'ready',root_id:'home', path:url.searchParams.get('path')||'', roots:[{id:'home',label:'Local Folders'}], entries:url.searchParams.get('path')?[]:[{name:'examples',path:'examples',type:'directory'}]}};
    if (url.pathname.endsWith('/events') && state.pendingEvents) await new Promise(()=>{});
    if (url.pathname.endsWith('/events')) return { body: '', contentType: 'text/event-stream' };
  });
  async function open(id) { if (width <= 620) await page.locator('#menu').click(); await page.locator('#sidebar .conversation-row > button').filter({ hasText: id.toUpperCase() + ' report' }).click(); await page.waitForFunction(title => !loading && document.querySelector('#conversation-title').textContent === title, id.toUpperCase() + ' report'); }
  return { page, open, state };
}
const hit = locator => locator.evaluate(node => { const r = node.getBoundingClientRect(); const h = document.elementFromPoint(r.x + r.width / 2, r.y + r.height / 2); return h === node || node.contains(h); });
const settle = page => page.evaluate(() => Promise.all(document.getAnimations().filter(a => a.effect?.getTiming().iterations !== Infinity).map(a => a.finished.catch(() => {}))));

(async () => {
 const browser=await chromium.launch(), failures=[];
 async function check(name, fn) {if(process.env.ONLY&&!process.env.ONLY.split(',').some(id=>name.startsWith(id)))return;try{await fn();console.log('PASS '+name);}catch(e){failures.push(name+': '+e.stack);console.error('FAIL '+name+': '+e.message);}}
 try {
 await check('A1-F1 full Pipeline decisions with enforcement metadata',async()=>{
  for(const theme of ['porcelain','amethyst','petroleum']){const f=await fixture(browser,1280,720);f.state.plan=true;f.state.running=true;await f.open('a');const p=f.page;await p.evaluate(t=>HarnessTheme.apply(t),theme);await p.evaluate(()=>runConsole.openRun('a-job'));await p.locator('.run-span-row').nth(2).waitFor();await settle(p);
   const geometry=await p.locator('.run-console-body').evaluate(b=>({scroll:b.scrollTop,top:b.getBoundingClientRect().top,bottom:b.getBoundingClientRect().bottom,items:[...b.querySelectorAll('.run-span-row,.run-plan-actions button')].map(n=>{const r=n.getBoundingClientRect();return {text:n.textContent,top:r.top,bottom:r.bottom,hit:n.contains(document.elementFromPoint(r.x+r.width/2,r.bottom-2))};})}));assert.equal(geometry.scroll,0);for(const item of geometry.items){assert(item.bottom<=geometry.bottom&&item.top>=geometry.top,JSON.stringify(geometry));assert(item.hit,JSON.stringify(item));}await capture(p,'pipeline-'+theme);await p.close();}
 });
 await check('A1-F2 sidebar backend disclosure',async()=>{const {page:p}=await fixture(browser);const chip=p.locator('#sidebar .backend-chip').first();await chip.hover();assert.equal(await chip.getAttribute('title'),'Codex');assert(await hit(chip));await p.close();});
 await check('A2-F1 completed and failed inbox polling retains logical focus',async()=>{for(const width of [1280,400])for(const state of ['completed','failed']){const f=await fixture(browser,width,900),p=f.page;f.state.jobs=[{...run,job_id:'b-job',conversation_id:'b',state,title:'Target run'}];await p.evaluate(filter=>runConsole.openAttention(filter),state==='completed'?'complete':'error');const action=p.getByRole('button',{name:'View run',exact:true});await action.focus();await p.waitForTimeout(4400);assert.equal(await p.evaluate(()=>document.activeElement.textContent),'View run');f.state.jobs[0].title='Updated target';await p.waitForTimeout(4200);assert.equal(await p.evaluate(()=>document.activeElement.textContent),'View run');assert(await hit(action));await p.keyboard.press('Enter');await p.locator('#needs-you-inbox').waitFor({state:'hidden'});await p.close();}});
 await check('A2-F3 unavailable preview reachable by listbox keyboard',async()=>{const f=await fixture(browser),p=f.page;f.state.resources=[{...resource,id:'enabled',name:'enabled'},{...resource,id:'blocked',name:'blocked',selectable:false,unavailable_reason:'Unavailable',source:'/synthetic/blocked',preflight_hint:'Synthetic keyboard remedy'}];await p.locator('#prompt').fill('/');await p.locator('#prompt').press('End');await p.locator('#prompt').press('ArrowDown');await p.waitForTimeout(150);let found=false;for(let i=0;i<=await p.locator('#resource-menu [role=option]').count();i++){await p.keyboard.press('ArrowDown');if((await p.locator('#resource-preview').innerText()).includes('Synthetic keyboard remedy')){found=true;break;}}assert(found);await p.keyboard.press('Enter');assert.equal(await p.locator('.resource-chip').count(),0);await p.close();});
 await check('A2-F4 short viewport preserves focused card identity and draft',async()=>{const f=await fixture(browser,720,406),p=f.page;await f.open('a');await p.locator('#prompt').fill('Exact draft');await p.evaluate(()=>runConsole.openRun('a-job'));const card=p.locator('.run-span-row').first();await card.waitFor();await card.focus();await p.waitForTimeout(250);assert(await hit(card));const b=await p.locator('.run-console-body').boundingBox(),c=await card.boundingBox();assert(b.height>=c.height,JSON.stringify({b,c}));assert.equal(await p.locator('#prompt').inputValue(),'Exact draft');await capture(p,'short-viewport');await p.close();});
 await check('A2-F4 native 200 percent zoom keeps console cards readable',async()=>{
  const os=require('node:os'),folder=await fs.mkdtemp(path.join(os.tmpdir(),'round7-zoom-')),ext=path.join(folder,'extension');await fs.mkdir(ext);await fs.writeFile(path.join(ext,'manifest.json'),JSON.stringify({manifest_version:3,name:'Isolated zoom regression',version:'1.0',permissions:['tabs'],host_permissions:['http://console.test/*'],background:{service_worker:'background.js'}}));await fs.writeFile(path.join(ext,'background.js'),'chrome.runtime.onInstalled.addListener(() => {});');
  const context=await chromium.launchPersistentContext(path.join(folder,'profile'),{viewport:null,channel:'chromium',args:['--window-size=1440,900','--disable-extensions-except='+ext,'--load-extension='+ext]});
  try{const p=context.pages()[0],f=await fixture({newPage:async()=>p});await f.open('a');const worker=context.serviceWorkers()[0]||await context.waitForEvent('serviceworker');assert.equal(await worker.evaluate(async()=>{const tab=(await chrome.tabs.query({})).find(tab=>tab.url.includes('console.test'));await chrome.tabs.setZoom(tab.id,2);return chrome.tabs.getZoom(tab.id);}),2);await p.waitForFunction(()=>devicePixelRatio===2&&innerWidth===720);if(await p.locator('#prompt').evaluate(n=>!!n.closest('[inert]')))await p.keyboard.press('Escape');await p.locator('#prompt').fill('Native zoom draft');await p.evaluate(()=>runConsole.openRun('a-job'));const card=p.locator('.run-span-row').first();await card.waitFor();for(const maximize of [false,true]){if(maximize){await p.locator('#run-console-maximize').focus();await p.keyboard.press('Enter');}await card.focus();await p.waitForTimeout(200);assert(await hit(card));const b=await p.locator('.run-console-body').boundingBox(),r=await card.boundingBox();assert(b.height>=r.height,JSON.stringify({b,r}));}assert.equal(await p.locator('#prompt').inputValue(),'Native zoom draft');await capture(p,'native-zoom');}finally{await context.close();await fs.rm(folder,{recursive:true,force:true});}
 });
 await check('A5-F1 the model picker offers no Maestro choice even if the server still reports it',async()=>{const f=await fixture(browser),p=f.page;f.state.maestro=true;await p.reload();await p.locator('#startup-gate').waitFor({state:'hidden'});assert.equal(await p.locator('#model option').filter({hasText:/maestro|auto plan/i}).count(),0);assert.doesNotMatch(await p.locator('#model-menu').innerText(),/maestro|auto plan/i);await p.close();});
 await check('A5-F2 pending plan replay stays read-only',async()=>{const f=await fixture(browser);f.state.plan=true;f.state.running=true;await f.open('a');const p=f.page;await p.evaluate(()=>{showGate({gate_id:'plan',kind:'maestro_plan',plan:{steps:[]}});});assert.equal(await p.locator('#maestro-plan-card, .maestro-plan-card button').count(),0);assert.doesNotMatch(await p.locator('#status').innerText(),/approve/i,await p.locator('#status').innerText());await p.close();});
 await check('A5-F3 unsent gate choices survive navigation and yield to authority',async()=>{for(const multi of [false,true]){const f=await fixture(browser),p=f.page;f.state.gate={gate_id:'choice',kind:'options',question:'Audience?',multi_select:multi,state:'pending',options:[{id:'staff',label:'Staff'},{id:'public',label:'Public'}]};f.state.running=true;await f.open('a');await p.getByLabel('Staff',{exact:true}).check();if(multi)await p.getByLabel('Public',{exact:true}).check();await f.open('b');await f.open('a');assert(await p.getByLabel('Staff',{exact:true}).isChecked());if(multi)assert(await p.getByLabel('Public',{exact:true}).isChecked());assert(await p.getByRole('button',{name:'Confirm choice',exact:true}).isEnabled());f.state.gate={...f.state.gate,state:'resolved',choice:'public'};await f.open('b');await f.open('a');assert(!(await p.getByLabel('Staff',{exact:true}).isChecked()));assert(await p.getByRole('button',{name:'Confirm choice',exact:true}).isDisabled());await p.close();}});
 } finally {await browser.close();}
 if(failures.length){console.error(failures.join('\n'));process.exitCode=1;}
})();
