"""Supply-chain hygiene (SEC-RC-15): Starlette floor, hashed locks and a pinned build backend.

``requirements.txt`` and ``agent_service/bridge-requirements.txt`` are generated by
``uv pip compile ... --generate-hashes`` and are never edited by hand.
"""

import re
import tomllib
from pathlib import Path

from packaging.requirements import Requirement
from packaging.version import Version

ROOT = Path(__file__).resolve().parents[1]
LOCK = ROOT / "requirements.txt"
BRIDGE_LOCK = ROOT / "agent_service/bridge-requirements.txt"
BUILD_INPUT = ROOT / "scripts/build-requirements.in"
LOCK_COMMAND = (
    "uv pip compile pyproject.toml scripts/build-requirements.in --universal "
    "--python-version 3.11 --generate-hashes -o requirements.txt"
)
BRIDGE_LOCK_COMMAND = (
    "uv pip compile scripts/bridge-requirements.in --universal "
    "--python-version 3.10 --generate-hashes -o agent_service/bridge-requirements.txt"
)
HASH = re.compile(r"--hash=sha256:[0-9a-f]{64}")


def pyproject():
    return tomllib.loads((ROOT / "pyproject.toml").read_text())


def lock_entries(path):
    """``{name: (version, [hashes])}``; continuation lines joined, comments dropped.

    Every requirement must be ``name==version`` (an environment marker is allowed) and carry
    its hashes: anything else fails here, which is what ``pip --require-hashes`` would refuse.
    """
    entries = {}
    text = re.sub(r"\\\n", " ", path.read_text())
    for line in text.splitlines():
        line = line.strip()
        if not line or line.startswith("#"):
            continue
        requirement, *options = line.split(" --hash=")
        hashes = [HASH.fullmatch("--hash=" + option.strip()) for option in options]
        assert hashes and all(hashes), f"unhashed or malformed lock line: {line[:80]}"
        parsed = Requirement(requirement)
        specifiers = list(parsed.specifier)
        assert [s.operator for s in specifiers] == ["=="], f"not pinned: {requirement}"
        assert not specifiers[0].version.endswith("*"), f"wildcard pin: {requirement}"
        entries[parsed.name.lower().replace("_", "-")] = (specifiers[0].version, hashes)
    return entries


def test_dependency_specifiers():
    dependencies = [Requirement(item) for item in pyproject()["project"]["dependencies"]]
    (starlette,) = [item for item in dependencies if item.name == "starlette"]
    lowers = [Version(s.version) for s in starlette.specifier if s.operator == ">="]
    assert lowers and max(lowers) >= Version("1.3.1")
    assert any(s.operator == "<" and s.version == "2" for s in starlette.specifier)
    locked = lock_entries(LOCK)
    assert [item.name for item in dependencies if item.name.lower() not in locked] == []
    assert Version(locked["starlette"][0]) >= Version("1.3.1")


def test_lock_is_hashed():
    header = "".join(
        line[1:].strip() + " " for line in LOCK.read_text().splitlines() if line.startswith("#")
    )
    assert LOCK_COMMAND in header, "the header must name the command that generated the lock"
    assert lock_entries(LOCK)


def test_build_backend_pinned():
    (requirement,) = [Requirement(item) for item in pyproject()["build-system"]["requires"]]
    specifiers = list(requirement.specifier)
    assert requirement.name == "setuptools"
    assert [s.operator for s in specifiers] == ["=="], "the build backend needs an exact pin"
    pin = specifiers[0].version
    assert BUILD_INPUT.read_text().split() == [f"setuptools=={pin}"]
    assert lock_entries(LOCK)["setuptools"][0] == pin


def test_bridge_lock_is_hashed():
    header = " ".join(
        line[1:].strip() for line in BRIDGE_LOCK.read_text().splitlines() if line.startswith("#")
    )
    assert BRIDGE_LOCK_COMMAND in header
    assert (ROOT / "scripts/bridge-requirements.in").read_text().splitlines() == [
        "mcp>=1.12,<2",
        "httpx>=0.27,<1",
    ]
    locked = lock_entries(BRIDGE_LOCK)
    assert {"mcp", "httpx"} <= locked.keys()
    assert "*.txt" in pyproject()["tool"]["setuptools"]["package-data"]["agent_service"]
