'use strict';
const $=id=>document.getElementById(id);
let state,settings,working=false,wizard=false,editing=null;
function say(text,error=false){$('feedback').hidden=false;$('feedback').textContent=text;$('feedback').classList.toggle('error',error);}
async function request(path,data){const r=await fetch('/api/'+path,data===undefined?{}:{method:'POST',headers:{'Content-Type':'application/json','X-Harness-Admin':'1'},body:JSON.stringify(data)});const value=await r.json();if(!r.ok)throw Error(value.error||'Falha na operação');return value;}
function dirty(){$('dirty').textContent='Alterações ainda não salvas';}
function element(tag,text,cls){const el=document.createElement(tag);if(text!==undefined)el.textContent=text;if(cls)el.className=cls;return el;}
function toggle(text,checked,change,detail){const label=element('label',undefined,'toggle-row');const input=element('input');input.type='checkbox';input.checked=checked;input.onchange=()=>{change(input.checked);dirty();};const span=element('span');span.append(element('strong',text));if(detail)span.append(element('small',detail));label.append(input,span);return label;}
function providerCard(info){
 const id=info.id,spec=settings.services[id],card=element('article',undefined,'provider-card');card.dataset.provider=id;
 const top=element('div',undefined,'provider-top');top.append(element('span',id==='claude'?'✳':id==='local'?'◈':'⌘','provider-logo'));
 const title=element('div',undefined,'provider-title');title.append(element('h3',info.name),element('small',id==='local'?'Inferência local · agente Codex':id==='deepseek'?'Sua chave · créditos DeepSeek · agente Codex':'CLI local · inferência na nuvem'));top.append(title,element('span',info.found?'Encontrado':'Não instalado','pill'+(info.found?' good':'')));card.append(top);
 const body=element('div',undefined,'provider-body'),meta=element('div',undefined,'provider-meta');meta.append(element('span',state.authentication[id]?(id==='local'?'● Servidor disponível':'● Autenticado'):info.credential_present?'Credencial encontrada · verificar':'Login não verificado'));
 const check=element('button',id==='local'?'Verificar modelos':'Verificar conta','button secondary');check.disabled=!info.found;check.hidden=id==='deepseek'&&!state.credentials?.deepseek;check.onclick=()=>action(async()=>{const data=await request('check',{provider:id});state.authentication[id]=data.authenticated;state.models[id]=data.models;renderProviders();say(data.authenticated?'Conta verificada. Escolha os modelos que deseja disponibilizar.':'Use Entrar para abrir a autorização pelo painel e depois verifique novamente.');});meta.append(check);if(id!=='local'&&id!=='deepseek'){const login=element('button','Entrar','button secondary');login.disabled=!info.found;login.onclick=()=>action(async()=>{await request('provider-login',{provider:id});say('Login iniciado. Acompanhe a autorização na seção de operações.');pollOperations();});meta.append(login);}body.append(meta);
 if(id==='deepseek'){const tokenLabel=element('label','Sua chave API DeepSeek (BYOK)'),token=element('input');token.type='password';token.autocomplete='off';token.placeholder=state.credentials?.deepseek?'Chave salva · preencha somente para substituir':'Cole sua chave da plataforma DeepSeek';tokenLabel.append(token);const saveToken=element('button','Salvar chave e verificar','button primary');saveToken.onclick=()=>action(async()=>{if(token.value){await request('provider-token',{provider:id,token:token.value});token.value='';}const result=await request('check',{provider:id});state.models[id]=result.models;state.authentication[id]=true;state.credentials={...state.credentials,deepseek:true};renderProviders();say('DeepSeek verificado. '+(result.balance?.balance_infos||[]).map(b=>b.currency+' '+b.total_balance).join(' · '));});body.append(tokenLabel,saveToken,element('p','A chave fica somente nesta máquina. Conversas, arquivos e ferramentas enviados ao modelo consomem créditos DeepSeek.','hint'));}

 const label=element('label','Modelos disponibilizados','field-label');body.append(label);
 const choices=element('div',undefined,'model-list');const models=id==='local'?(info.models||Object.keys(state.models[id]||{})):Object.keys(state.models[id]||{});for(const m of new Set([...models,...spec.models]))choices.append(toggle(m,spec.models.includes(m),yes=>{spec.models=yes?[...spec.models,m]:spec.models.filter(x=>x!==m);if(id==='local')renderProfile();}));
 if(!choices.children.length)choices.append(element('p','Verifique a conta para listar os modelos.','hint'));body.append(choices);
 if(id==='claude')body.append(element('p','Sonnet, Opus e Haiku são aliases do CLI. O acesso real depende da sua conta.','hint'));
 const permissions=element('div',undefined,'permissions');for(const [key,name] of [['read','Ler pastas'],['write','Alterar arquivos'],['upload','Receber anexos'],['internet','Internet'],['shell','Terminal'],['hooks','Hooks do CLI']])permissions.append(toggle(name,!!spec.permissions[key],yes=>{spec.permissions[key]=yes;if(yes&&['internet','shell','hooks'].includes(key))spec.mode='native';if(yes&&key==='upload'){settings.uploads_enabled=true;$('uploads').checked=true;}select.value=spec.mode;}));const advanced=element('details',undefined,'advanced');advanced.append(element('summary','Ajustar permissões e integrações'));advanced.append(permissions);body.append(advanced);
 const mode=element('label','Modo de execução'),select=element('select');for(const [v,label] of [['scoped','Isolado · ferramentas de projeto'],['native','CLI nativo · ferramentas e conectores']]){const o=element('option',label);o.value=v;select.append(o);}select.value=spec.mode||'scoped';select.onchange=()=>{spec.mode=select.value;dirty();};mode.append(select);if(!['local','deepseek'].includes(id))advanced.append(mode);
 advanced.append(element('p','Modo nativo usa as permissões do CLI e os acessos próprios dos conectores. A leitura não fica limitada pelas pastas do modo isolado. Terminal, hooks e plugins podem ampliar leitura, escrita e rede conforme a política do CLI. Internet controla ferramentas web/rede do agente, não é um firewall para conectores.','hint'));
 const connectors=element('label','Conectores / plugins selecionados'),connectorList=element('div',undefined,'model-list');for(const c of state.integrations?.[id]||[]){connectorList.append(toggle(c.name,(spec.integrations||[]).includes(c.id),yes=>{spec.integrations=spec.integrations||[];spec.integrations=yes?[...spec.integrations,c.id]:spec.integrations.filter(x=>x!==c.id);}));}if(!connectorList.children.length)connectorList.append(element('p','Nenhuma integração cadastrada. Use a seção de conectores.','hint'));connectors.append(connectorList);advanced.append(connectors);
 card.append(body);const bottom=element('div',undefined,'provider-enabled');bottom.append(toggle('Disponibilizar este serviço',spec.enabled,yes=>spec.enabled=yes));card.append(bottom);return card;
}
function renderProviders(){
 $('provider-options').replaceChildren(...state.inventory.services.filter(info=>!settings.services[info.id]?.added&&!settings.services[info.id]?.enabled&&!settings.services[info.id]?.models?.length).map(info=>{const button=element('button',info.name+' · '+(info.api?'API / BYOK':info.found?'Encontrado':'Não instalado'),'button secondary');button.onclick=()=>{editing=info.id;renderProviders();};return button;}));
 $('provider-options').hidden=!!editing;
 const info=state.inventory.services.find(x=>x.id===editing);$('provider-cards').replaceChildren(...(info?[providerCard(info)]:[]));$('permission-editor').replaceChildren();
 if(info){const advanced=$('provider-cards').querySelector('.advanced');advanced.open=true;$('permission-editor').append(advanced);}
 renderDashboard();
}
function renderDashboard(){const configured=state.inventory.services.filter(i=>{const s=settings.services[i.id];return s&&(s.added||s.enabled||s.models.length);});$('configured-providers').replaceChildren(...configured.map(info=>{const s=settings.services[info.id],card=element('article',undefined,'panel configured-card');card.classList.toggle('selected',editing===info.id);card.dataset.configuredProvider=info.id;const heading=element('div',undefined,'configured-heading'),mark=element('span',undefined,'provider-logo');mark.append(icon('layers'));heading.append(mark,element('h3',info.name));card.append(heading,element('span',s.enabled?'Habilitado':'Desativado','pill'+(s.enabled?' good':'')),element('p',s.models.join(' · ')||'Nenhum modelo selecionado','configured-models'));const actions=element('div',undefined,'card-actions');const edit=element('button','Editar','button secondary');edit.setAttribute('aria-label','Editar '+info.name);edit.onclick=()=>openWizard(info.id);const remove=element('button','Excluir','button secondary');remove.onclick=()=>action(async()=>{if(!confirm('Remover '+info.name+' do painel? A conta e o CLI não serão desinstalados. A chave BYOK deste provedor será apagada.'))return;await request('provider-delete',{provider:info.id});await load();say('Provedor removido.');});edit.prepend(icon('edit'));remove.prepend(icon('trash'));actions.append(edit,remove);card.append(actions);return card;}));if(!configured.length)$('configured-providers').append(element('p','Seu espaço está pronto. Adicione um provedor para escolher modelos e permissões.','empty-state'));}
function openWizard(provider=null){if(wizard&&editing!==provider&&!confirm('Descartar a edição atual e abrir outro provedor?'))return;settings=structuredClone(state.settings);wizard=true;editing=provider;step=0;renderProviders();renderProjects();showStep(0);$('wizard-title').textContent=provider?'Editar provedor':'Adicionar provedor';$('provider-dialog').hidden=false;renderProfile();$('wizard-feedback').append($('feedback'));}
function dashboard(){wizard=false;editing=null;showStep(0);renderDashboard();}

function renderProjects(){
 const projects=new Map();for(const p of state.inventory.projects)projects.set(p.path,{root:p.path,label:p.name,id:p.name.toLowerCase().replace(/[^a-z0-9_-]/g,'-')});for(const p of settings.projects)projects.set(p.root,p);
 const rows=[];const none=element('div',undefined,'project-row');none.append(element('span','◌'));const noneLabel=element('div');noneLabel.append(element('strong','Conversas sem projeto'),element('small','Sem pasta de projeto vinculada; modo nativo segue a política do CLI'));none.append(noneLabel);rows.push(none);
 for(const p of projects.values()){
  const row=element('div',undefined,'project-row'),selected=settings.projects.some(x=>x.root===p.root);
  const choice=toggle(p.label,selected,yes=>{if(yes){if(settings.projects.some(x=>x.id===p.id))p.id+='-'+Math.random().toString(36).slice(2,6);settings.projects.push(p);}else{settings.projects=settings.projects.filter(x=>x.root!==p.root);for(const s of Object.values(settings.services))s.projects=s.projects.filter(x=>x!==p.id);}renderProjects();},p.root);row.append(choice);
  const badges=element('div',undefined,'project-badges');if(selected)for(const [id,s] of Object.entries(settings.services).filter(([id])=>!editing||id===editing))badges.append(toggle(id,s.projects.includes(p.id),yes=>s.projects=yes?[...s.projects,p.id]:s.projects.filter(x=>x!==p.id)));row.append(badges);rows.push(row);
 }
 $('project-list').replaceChildren(...rows);$('project-count').textContent=settings.projects.length;
}
function renderStatus(){const s=state.status;if(s.startup_error)say("Não foi possível retomar o harness: "+s.startup_error,true);$('runtime-badge').textContent=s.running?'● Harness ativo':'● Harness parado';$('harness-state').textContent=s.running?'Ativo':'Parado';$('runtime-badge').classList.toggle('good',s.running);$('network-state').textContent=s.shared?'Compartilhado':'Local';$('network-detail').textContent=s.shared?'Apenas identidades autorizadas':'Compartilhamento desativado';$('tailscale-badge').textContent=state.inventory.network.online?'Conectado':'Desconectado';$('share').textContent=s.shared?'Retirar da Tailscale':'Habilitar na Tailscale';$('harness-link').textContent=s.shared?s.remote_url:s.local_url;$('harness-link').href=s.shared?s.remote_url:s.local_url;$('start').disabled=s.running;$('stop').disabled=!s.running;$('save').disabled=s.running;$('share').disabled=!state.inventory.network.online||(!s.running&&!s.shared);}
function render(){renderProviders();renderProjects();renderStatus();renderProfile();showStep(step);$('found-count').textContent=state.inventory.services.filter(x=>x.found).length;$('uploads').checked=settings.uploads_enabled;$('vpn-bind').value=settings.vpn_bind||'127.0.0.1';$('port').value=settings.port;$('tailnet-port').value=settings.tailnet_port;$('logins').value=settings.logins.join('\n');$('platform-note').textContent='Plataforma detectada: '+state.inventory.platform+'. Modo isolado requer Linux e bubblewrap. O modo nativo usa os mecanismos do CLI instalado.';}
async function load(){state=await request('state');settings=structuredClone(state.settings);render();}
async function action(fn){if(working)return;working=true;document.body.setAttribute('aria-busy','true');try{await fn();}catch(e){say(e.message,true);}finally{working=false;document.body.removeAttribute('aria-busy');}}
function collect(){settings.vpn_bind=$('vpn-bind').value.trim();settings.uploads_enabled=$('uploads').checked;settings.port=Number($('port').value);settings.tailnet_port=Number($('tailnet-port').value);settings.logins=$('logins').value.split('\n').map(x=>x.trim()).filter(Boolean);return settings;}
$('scan').onclick=()=>action(async()=>{state.inventory=await request('scan',{});renderProviders();renderProjects();renderStatus();say('Verificação concluída. Nenhuma permissão foi habilitada.');});
$('save').onclick=()=>action(async()=>{if(!editing)throw Error('Escolha um provedor.');settings.services[editing].added=true;await request('settings',collect());wizard=false;editing=null;await load();$('dirty').textContent='Escolhas salvas';say('Provedor salvo no dashboard.');});
$('start').onclick=()=>action(async()=>{await request('settings',collect());say('Verificando as contas e iniciando o harness…');await request('start',{});await load();say('Harness pronto. Abra o endereço de acesso.');});
$('stop').onclick=()=>action(async()=>{await request('stop',{});await load();say('Harness parado. O histórico foi preservado.');});
$('share').onclick=()=>action(async()=>{await request('tailnet',{enabled:!state.status.shared});await load();say(state.status.shared?'Acesso Tailscale habilitado.':'Rota deste harness retirada.');});
$('copy-link').onclick=()=>action(async()=>{await navigator.clipboard.writeText($('harness-link').href);say('Endereço copiado.');});
$('uploads').onchange=()=>{settings.uploads_enabled=$('uploads').checked;if(!settings.uploads_enabled)for(const s of Object.values(settings.services))s.permissions.upload=false;renderProviders();dirty();};
for(const id of ['port','tailnet-port','logins','vpn-bind'])$(id).oninput=dirty;
$('add-project').onclick=()=>$('folder-dialog').showModal();$('close-dialog').onclick=()=>$('folder-dialog').close();
$('folder-form').onsubmit=e=>{e.preventDefault();const label=$('folder-name').value.trim(),root=$('folder-path').value.trim(),id=label.toLowerCase().replace(/[^a-z0-9_-]/g,'-');if(settings.projects.some(p=>p.id===id||p.root===root)){say('Esse nome ou caminho já foi adicionado.',true);return;}settings.projects.push({id,label,root});renderProjects();dirty();$('folder-dialog').close();};
$('theme').onclick=()=>{document.documentElement.classList.toggle('light');localStorage.setItem('theme',document.documentElement.classList.contains('light')?'light':'dark');};if(localStorage.getItem('theme')==='light')document.documentElement.classList.add('light');
$('integration-run').onclick=()=>action(async()=>{
 const transport=$('integration-transport').value,source=$('integration-source').value.trim();
 const data={provider:$('integration-provider').value,action:$('integration-action').value,name:$('integration-name').value.trim(),transport,url:source};
 if(transport==='stdio'&&data.action==='connector_add')data.command=JSON.parse(source);
 await request('integration',data);say('Operação iniciada. Acompanhe o resultado abaixo.');pollOperations();
});
$('integration-refresh').onclick=()=>action(async()=>{const fresh=await request('state');state.integrations=fresh.integrations;renderProviders();say('Integrações atualizadas. Selecione-as no cartão do serviço.');});
$('install-model-button').onclick=()=>action(async()=>{await request('model-install',{model:$('install-model').value,accepted:$('model-consent').checked,runtime:$('install-runtime').value});say('Download iniciado. Acompanhe o progresso em Operações.');pollOperations();});
$('vpn-key').onclick=()=>action(async()=>{const value=await request('vpn-key',{});$('vpn-token').textContent=value.token;$('vpn-token').hidden=false;setTimeout(()=>{$('vpn-token').textContent='';$('vpn-token').hidden=true;},30000);});
let operationTimer;
async function pollOperations(){try{
 const fresh=await request('state');const jobs=fresh.operations||[];
 $('operations').replaceChildren(...jobs.map(j=>{const d=element('details');d.open=j.state==='running';d.append(element('summary','Operação '+j.id.slice(0,6)+' · '+j.state));const pre=element('pre',j.output||'Aguardando o CLI…');d.append(pre);
 for(const match of (j.output||'').matchAll(/https:\/\/[^\s<>"']+/g)){try{const url=new URL(match[0]);const link=element('a','Abrir autenticação ↗');link.href=url.href;link.target='_blank';link.rel='noopener noreferrer';d.append(link);}catch{}}
 if(j.state==='running'){const cancel=element('button','Cancelar','button secondary');cancel.onclick=()=>action(async()=>{await request('cancel-operation',{id:j.id});pollOperations();});d.append(cancel);}return d;}));
 clearTimeout(operationTimer);if(jobs.some(j=>j.state==='running'))operationTimer=setTimeout(pollOperations,2000);
}catch(e){say(e.message,true);}}


$('local-files').onclick=()=>action(async()=>{const result=await request('local-files',{folder:$('model-folder').value});$('local-file').replaceChildren(...result.files.map(f=>{const o=element('option',f.name+' · '+(f.bytes/1024**3).toFixed(1)+' GiB');o.value=f.path;return o;}));if(result.servers[0])$('llama-binary').value=result.servers[0].binary;say(result.files.length+' arquivos encontrados. Servidores existentes: '+result.servers.length+'.');});
$('local-start').onclick=()=>action(async()=>{await request('local-start',{file:$('local-file').value,binary:$('llama-binary').value,gpu_layers:Number($('gpu-layers').value),use_profile:$('use-profile').checked});say('Servidor iniciando. Acompanhe Operações e atualize o inventário após o carregamento.');pollOperations();});

const providerDialog=element('section');providerDialog.id='provider-dialog';providerDialog.setAttribute('aria-labelledby','wizard-title');
const workspace=element('div',undefined,'provider-workspace');$('configured-providers').before(workspace);workspace.append($('configured-providers'),providerDialog);const emptyInspector=element('div','Selecione um provedor para ver modelos, pesos, permissões e configuração.','inspector-empty');emptyInspector.id='inspector-empty';workspace.append(emptyInspector);
const wizardContent=element('div',undefined,'wizard-content');
const inspectorTabs=element('div',undefined,'inspector-tabs');inspectorTabs.id='inspector-tabs';for(const [index,label] of ['Modelo e hardware','Permissões e projetos','Resumo'].entries()){const button=element('button',label,'button secondary');button.onclick=()=>showStep(index);inspectorTabs.append(button);}providerDialog.append($('wizard-heading'),inspectorTabs,wizardContent);
const wizardFeedback=element('div');wizardFeedback.id='wizard-feedback';wizardContent.append(wizardFeedback);
for(const id of ['local-models','providers','projects','integrations','review'])wizardContent.append($(id));
const wizardFooter=element('div',undefined,'wizard-footer');wizardFooter.append($('wizard-back'),$('wizard-progress'),$('wizard-next'),$('save'));providerDialog.append(wizardFooter);

function icon(name){const paths={plus:'M12 5v14M5 12h14',layers:'m12 3 9 5-9 5-9-5 9-5ZM3 12l9 5 9-5M3 16l9 5 9-5',edit:'m16 3 5 5-12 12H4v-5L16 3ZM13 6l5 5',trash:'M3 6h18M9 6V3h6v3M5 6l1 15h12l1-15M10 10v7M14 10v7',scan:'M8 3H3v5M16 3h5v5M21 16v5h-5M8 21H3v-5M8 12h8'};const svg=document.createElementNS('http://www.w3.org/2000/svg','svg');svg.setAttribute('viewBox','0 0 24 24');svg.setAttribute('aria-hidden','true');svg.classList.add('ui-icon');const path=document.createElementNS(svg.namespaceURI,'path');path.setAttribute('d',paths[name]||paths.layers);svg.append(path);return svg;}
for(const [id,name,text] of [['add-provider','plus','Adicionar provedor'],['scan','scan','Verificar ambiente'],['add-project','plus','Adicionar pasta']]){$(id).replaceChildren(icon(name),document.createTextNode(text));}
let step=0;
const steps=['providers','projects','network'];
function showStep(value){step=Math.max(0,Math.min(2,value));$('dashboard').hidden=false;if(!wizard){$('provider-dialog').hidden=true;$('main').insertBefore($('feedback'),$('overview'));}$('wizard-heading').hidden=!wizard;$('inspector-empty').hidden=wizard;const existing=!!(editing&&(state.settings.services[editing]?.added||state.settings.services[editing]?.enabled));$('inspector-tabs').hidden=!existing;[...$('inspector-tabs').children].forEach((b,i)=>b.setAttribute('aria-pressed',String(i===step)));$('provider-dialog').hidden=!wizard;$('provider-dialog').classList.toggle('local-inspector',editing==='local');$('network').hidden=true;document.querySelectorAll('[data-step]').forEach(el=>el.hidden=!wizard||Number(el.dataset.step)!==step||(el.id==='local-models'&&editing!=='local'));$('wizard-progress').textContent=wizard?'Etapa '+(step+1)+' de 3':'';$('wizard-back').hidden=!wizard||existing||step===0;$('wizard-next').hidden=!wizard||existing||step===2;$('save').hidden=!wizard||(!existing&&step!==2);$('save').textContent=existing?'Salvar alterações':'Concluir e salvar';$('wizard-progress').hidden=existing;for(const id of ['start','stop'])$(id).hidden=wizard;if(editing){const s=settings.services[editing];$('provider-review').textContent=editing+' · '+s.models.join(', ')+' · '+s.projects.length+' projetos · '+(s.enabled?'disponível para execução':'desativado');}}
$('wizard-back').onclick=()=>showStep(step-1);$('wizard-next').onclick=()=>{if(!editing){say('Escolha um provedor para continuar.',true);return;}if(step===0&&!settings.services[editing].models.length){say('Verifique a conta e selecione pelo menos um modelo.',true);return;}showStep(step+1);};
$('add-provider').onclick=()=>action(async()=>{const button=$('add-provider');button.disabled=true;try{state.inventory=await request('scan',{});openWizard();}finally{button.disabled=false;}});$('nav-dashboard').onclick=e=>{e.preventDefault();action(async()=>{wizard=false;await load();});};$('wizard-cancel').onclick=()=>action(async()=>{wizard=false;editing=null;await load();say('Edição descartada.');});$('manage-network').onclick=()=>{$('network').hidden=!$('network').hidden;};
function renderProfile(){
 const profile=state.local_profile||{},p=profile.performance||{};
 const runtimes=state.inventory.services.find(x=>x.id==='local')?.runtimes||[];
 const selected=settings.services.local?.models||[];
 const active=runtimes.find(r=>selected.includes(r.id));
 const summary=$('local-profile-summary');summary.replaceChildren();
 function section(title,rows){const card=element('section',undefined,'hardware-card');card.append(element('h3',title));for(const [name,value] of rows){const row=element('div',undefined,'hardware-row');row.append(element('span',name),element('strong',value??'Não informado'));card.append(row);}return card;}
 const file=profile.model_file;
 summary.append(section('Modelo e pesos',[
  ['Selecionado no harness',selected.join(' · ')||'Nenhum modelo'],
  ['Arquivo de pesos salvo',file?file.split('/').pop():'Sem perfil salvo'],
  ['Servidor verificado',active?active.runtime+' · '+active.id:'Não verificado para o modelo selecionado'],
  ['Pesos do processo',active?.model_file?.split('/').pop()||'Não informado']
 ]));
 const grid=element('div',undefined,'hardware-grid');
 grid.append(section('GPU · perfil salvo',[['Dispositivo',p.device],['Camadas solicitadas',p['n-gpu-layers']],['Camadas efetivamente carregadas','Não aferido'],['VRAM em uso','Sem telemetria']]),section('CPU · perfil salvo',[['Camadas MoE na CPU',p['n-cpu-moe']],['CPUs lógicas',p['cpu-range']],['CPUs no lote',p['cpu-range-batch']],['Threads / lote',[p.threads??'—',p['threads-batch']??'—'].join(' / ')]]));summary.append(grid);
 if(active){const perf=active.performance||{};const running=element('details',undefined,'advanced');running.append(element('summary','Parâmetros do processo em execução'));running.append(section('Argumentos detectados no processo',[['GPU · camadas solicitadas',perf['n-gpu-layers']],['CPU · camadas MoE',perf['n-cpu-moe']],['CPUs lógicas',perf['cpu-range']],['Contexto configurado',perf['ctx-size']]]));summary.append(running);}
 summary.append(element('p','Perfil salvo e argumentos do processo não comprovam a alocação efetiva. VRAM, RAM e camadas carregadas só serão exibidas quando medidas.','hint'));
 if(file){const details=element('details');details.append(element('summary','Caminho completo dos pesos'),element('p',file,'hint'));summary.append(details);}
 $('dashboard-profile').textContent=file?file.split('/').pop()+' · perfil privado salvo':'Nenhum perfil salvo.';
 $('local-import').hidden=!active;$('use-profile').checked=!!file;$('use-profile').disabled=!file;
 if(profile.binary)$('llama-binary').value=profile.binary;
 if(file){const o=element('option',file.split('/').pop());o.value=file;$('local-file').replaceChildren(o);}
 if(p['n-gpu-layers']!==undefined)$('gpu-layers').value=p['n-gpu-layers'];
}
$('local-import').onclick=()=>action(async()=>{state.local_profile=await request('local-import',{});renderProfile();say('Perfil salvo somente nesta máquina. O servidor em execução foi preservado.');});
action(async()=>{await load();pollOperations();});

let importBundle=null;
$('export-settings').onclick=()=>action(async()=>{const bundle=await request('settings-export',{});const url=URL.createObjectURL(new Blob([JSON.stringify(bundle,null,2)],{type:'application/json'}));const link=element('a');link.href=url;link.download='tail-harness-settings.json';link.click();setTimeout(()=>URL.revokeObjectURL(url),1000);say('Configuração salva exportada sem credenciais. Alterações ainda não salvas não entram no arquivo.');});
$('import-settings').onchange=()=>action(async()=>{importBundle=null;$('import-preview').hidden=true;const file=$('import-settings').files[0];if(!file)return;if(file.size>60000)throw Error('Arquivo de configuração muito grande.');const candidate=JSON.parse(await file.text());const preview=await request('settings-import',{bundle:candidate,apply:false});importBundle=candidate;$('import-summary').textContent='Substituir escolhas salvas: '+preview.services.join(', ')+' · '+preview.projects+' projetos'+(preview.local_profile?' · inclui perfil local':' · mantém o perfil local atual')+'. A importação não inicia serviços.';$('import-preview').hidden=false;});
$('apply-import').onclick=()=>action(async()=>{if(!importBundle)return;await request('settings-import',{bundle:importBundle,apply:true});importBundle=null;$('import-preview').hidden=true;await load();say('Configuração importada. Revise as etapas antes de iniciar.');});
$('cancel-import').onclick=()=>{importBundle=null;$('import-preview').hidden=true;$('import-settings').value='';};

$('save-network').onclick=()=>action(async()=>{await request('settings',collect());await load();$('network').hidden=false;say('Acesso remoto salvo. Inicie o harness para aplicar.');});
